export type PublicMediaStatus = "approved" | "review-required" | "excluded";
export type ProofStatus = "watchable-platform-visual" | "watchable-style-reference" | "unverified-result" | "not-public-proof";

export type HomepageMediaAsset = {
  assetId: string;
  sourceSystem: string;
  creatorOwner: string;
  publicSafeStatus: PublicMediaStatus;
  consentUsageStatus: string;
  mediaKind: "motion" | "static";
  mobileSafe: boolean;
  desktopSafe: boolean;
  resolution: string;
  durationSeconds: number | null;
  type: string;
  whatItProves: string;
  sourceAsset: string | null;
  outputAsset: string | null;
  proofStatus: ProofStatus;
  fallbackAsset: string;
  livePath: string;
  workingStatus: "ready" | "review-required" | "excluded";
};

/**
 * Canonical public/showcase media registry.
 *
 * Assets are public-facing only when their repository provenance documents that
 * intent or their owning product record is already public. This registry never
 * upgrades a style reference into a creator-result claim.
 */
export const HOMEPAGE_MEDIA: Record<string, HomepageMediaAsset> = {
  kingcamHero: {
    assetId: "kingcam-hero-cam",
    sourceSystem: "KingCam clone campaign",
    creatorOwner: "KingCam / CreatorVault",
    publicSafeStatus: "approved",
    consentUsageStatus: "CreatorVault-owned public campaign asset; tracked in the VaultX trailer provenance record.",
    mediaKind: "motion",
    mobileSafe: true,
    desktopSafe: true,
    resolution: "1080x1920",
    durationSeconds: 5.042,
    type: "Founder identity motion",
    whatItProves: "KingCam is the face of CreatorVault.",
    sourceAsset: "/uploads/vaultx/homepage-trailer/platform_native_pollo_kling3_latest.mp4",
    outputAsset: "/videos/vaultx-homepage-kingcam-trailer.mp4",
    proofStatus: "watchable-platform-visual",
    fallbackAsset: "/assets/kingcam-hero.jpg",
    livePath: "/videos/kingcam-hero-cam.mp4",
    workingStatus: "ready",
  },
  womenCreatorMotion: {
    assetId: "platform-dashboard-hero",
    sourceSystem: "CreatorVault platform hero library",
    creatorOwner: "CreatorVault",
    publicSafeStatus: "approved",
    consentUsageStatus: "Added in the repository’s approved four-page hero-media release.",
    mediaKind: "motion",
    mobileSafe: true,
    desktopSafe: true,
    resolution: "704x1248",
    durationSeconds: 5.042,
    type: "Creator-at-work motion",
    whatItProves: "A woman creator is visibly operating her business.",
    sourceAsset: null,
    outputAsset: "/videos/platform/dashboard-hero.mp4",
    proofStatus: "watchable-platform-visual",
    fallbackAsset: "/images/vaultx/vaultx-business-presenter-mobile.png",
    livePath: "/videos/platform/dashboard-hero.mp4",
    workingStatus: "ready",
  },
  womenCreatorAudienceMotion: {
    assetId: "platform-marketplace-hero",
    sourceSystem: "CreatorVault platform hero library",
    creatorOwner: "CreatorVault",
    publicSafeStatus: "approved",
    consentUsageStatus: "Existing public platform hero asset; its repository history documents dedicated public-route deployment.",
    mediaKind: "motion",
    mobileSafe: true,
    desktopSafe: true,
    resolution: "704x1248",
    durationSeconds: 5.042,
    type: "Creator-and-audience motion",
    whatItProves: "Creator content and fan attention belong in the same experience.",
    sourceAsset: null,
    outputAsset: "/videos/platform/marketplace-hero.mp4",
    proofStatus: "watchable-platform-visual",
    fallbackAsset: "/images/vaultx/vaultx-business-presenter-hero.png",
    livePath: "/videos/platform/marketplace-hero.mp4",
    workingStatus: "ready",
  },
  bodyCinemaConcept: {
    assetId: "body-cinema-transformation-reference",
    sourceSystem: "Body Cinema visual library",
    creatorOwner: "CreatorVault",
    publicSafeStatus: "review-required",
    consentUsageStatus: "Repository asset is public-facing, but creator/model usage clearance is not embedded with the file.",
    mediaKind: "motion",
    mobileSafe: true,
    desktopSafe: true,
    resolution: "720x1280",
    durationSeconds: 4.01,
    type: "Before-and-after creative reference",
    whatItProves: "A cinematic transformation visual exists; it does not prove a creator-specific Body Cinema result.",
    sourceAsset: null,
    outputAsset: "/assets/hero-transformation.mp4",
    proofStatus: "unverified-result",
    fallbackAsset: "/images/platform/body-cinema-feature-proof.webp",
    livePath: "/assets/hero-transformation.mp4",
    workingStatus: "review-required",
  },
  bodyCinemaIntelligenceReference: {
    assetId: "body-cinema-intelligence-reference",
    sourceSystem: "Body Cinema visual library",
    creatorOwner: "CreatorVault",
    publicSafeStatus: "review-required",
    consentUsageStatus: "Repository asset is public-facing, but creator/model usage clearance is not embedded with the file.",
    mediaKind: "motion",
    mobileSafe: true,
    desktopSafe: true,
    resolution: "720x1280",
    durationSeconds: 4.01,
    type: "Intelligence visual reference",
    whatItProves: "The product’s intended analysis language, not analysis of a public creator source.",
    sourceAsset: null,
    outputAsset: "/assets/intelligence-overlay.mp4",
    proofStatus: "unverified-result",
    fallbackAsset: "/images/platform/body-cinema-hero.webp",
    livePath: "/assets/intelligence-overlay.mp4",
    workingStatus: "review-required",
  },
  vaultxRevenueVisual: {
    assetId: "vaultx-hero",
    sourceSystem: "VaultX public product visual",
    creatorOwner: "CreatorVault",
    publicSafeStatus: "approved",
    consentUsageStatus: "Existing deployed VaultX public product asset.",
    mediaKind: "motion",
    mobileSafe: true,
    desktopSafe: true,
    resolution: "720x1280",
    durationSeconds: 4.75,
    type: "VaultX product visual",
    whatItProves: "VaultX is a visible premium content-and-revenue workspace.",
    sourceAsset: null,
    outputAsset: "/videos/platform/vaultx-hero.mp4",
    proofStatus: "watchable-platform-visual",
    fallbackAsset: "/images/platform/vaultx-hero.webp",
    livePath: "/videos/platform/vaultx-hero.mp4",
    workingStatus: "ready",
  },
  vaultxTrailer: {
    assetId: "vaultx-cinematic-trailer",
    sourceSystem: "VaultX cinematic trailer",
    creatorOwner: "CreatorVault",
    publicSafeStatus: "approved",
    consentUsageStatus: "Repository public trailer asset with matching public poster.",
    mediaKind: "motion",
    mobileSafe: true,
    desktopSafe: true,
    resolution: "1280x720",
    durationSeconds: 28.778,
    type: "Product walkthrough motion",
    whatItProves: "VaultX product language and vertical-video workflow.",
    sourceAsset: null,
    outputAsset: "/videos/vaultx-cinematic-trailer.mp4",
    proofStatus: "watchable-platform-visual",
    fallbackAsset: "/videos/vaultx-cinematic-trailer-poster.png",
    livePath: "/videos/vaultx-cinematic-trailer.mp4",
    workingStatus: "ready",
  },
  kingcamCampaignSource: {
    assetId: "kingcam-platform-native-source",
    sourceSystem: "CreatorVault native KingCam production",
    creatorOwner: "KingCam / CreatorVault",
    publicSafeStatus: "approved",
    consentUsageStatus: "Recorded as the CreatorVault-native source asset in the public trailer provenance record.",
    mediaKind: "motion",
    mobileSafe: true,
    desktopSafe: true,
    resolution: "1920x1080",
    durationSeconds: 5.042,
    type: "Campaign source motion",
    whatItProves: "A persisted platform-native source clip exists before the public founder trailer.",
    sourceAsset: null,
    outputAsset: "/videos/vaultx-homepage-kingcam-trailer.mp4",
    proofStatus: "watchable-platform-visual",
    fallbackAsset: "/videos/vaultx-homepage-kingcam-trailer-poster.jpg",
    livePath: "/uploads/vaultx/homepage-trailer/platform_native_pollo_kling3_latest.mp4",
    workingStatus: "ready",
  },
  kingcamPlatformTrailer: {
    assetId: "vaultx-homepage-kingcam-trailer",
    sourceSystem: "CreatorVault native KingCam production",
    creatorOwner: "KingCam / CreatorVault",
    publicSafeStatus: "approved",
    consentUsageStatus: "Provenance file records CreatorVault-native production and intended public homepage output.",
    mediaKind: "motion",
    mobileSafe: true,
    desktopSafe: true,
    resolution: "1920x1080",
    durationSeconds: 18,
    type: "Founder and platform trailer",
    whatItProves: "CreatorVault has a persisted, platform-native motion trailer.",
    sourceAsset: "/uploads/vaultx/homepage-trailer/platform_native_pollo_kling3_latest.mp4",
    outputAsset: "/videos/vaultx-homepage-kingcam-trailer.mp4",
    proofStatus: "watchable-platform-visual",
    fallbackAsset: "/videos/vaultx-homepage-kingcam-trailer-poster.jpg",
    livePath: "/videos/vaultx-homepage-kingcam-trailer.mp4",
    workingStatus: "ready",
  },
  premiumUnlockVisual: {
    assetId: "vaultx-final-drop",
    sourceSystem: "VaultX visual library",
    creatorOwner: "CreatorVault",
    publicSafeStatus: "approved",
    consentUsageStatus: "Existing public project asset with no depicted creator or external personal data.",
    mediaKind: "motion",
    mobileSafe: true,
    desktopSafe: true,
    resolution: "720x1280",
    durationSeconds: 4.01,
    type: "Premium offer motion",
    whatItProves: "The visual mechanics of a premium unlock without claiming a completed sale or earnings amount.",
    sourceAsset: null,
    outputAsset: "/assets/final-drop.mp4",
    proofStatus: "watchable-platform-visual",
    fallbackAsset: "/images/platform/vaultx-feature-ppv.webp",
    livePath: "/assets/final-drop.mp4",
    workingStatus: "ready",
  },
  creationArsenal: {
    assetId: "creatorvault-reel-arsenal",
    sourceSystem: "CreatorVault reel library",
    creatorOwner: "CreatorVault",
    publicSafeStatus: "approved",
    consentUsageStatus: "Existing public project assets showing CreatorVault creative outputs.",
    mediaKind: "static",
    mobileSafe: true,
    desktopSafe: true,
    resolution: "Assorted output canvases",
    durationSeconds: null,
    type: "Creation output collection",
    whatItProves: "The platform represents multiple creation categories without inventing a result or revenue claim.",
    sourceAsset: null,
    outputAsset: null,
    proofStatus: "watchable-platform-visual",
    fallbackAsset: "/images/reel/reel-cinematic-trailer.png",
    livePath: "/images/reel/reel-cinematic-trailer.png",
    workingStatus: "ready",
  },
  socialVisual: {
    assetId: "creatorvault-native-social-record",
    sourceSystem: "Canonical Social Empire",
    creatorOwner: "KingCam / CreatorVault",
    publicSafeStatus: "review-required",
    consentUsageStatus: "A real native post and approval-gated external drafts exist, but no public screenshot or public media output has a verified serving path in this release.",
    mediaKind: "static",
    mobileSafe: true,
    desktopSafe: true,
    resolution: "Record-backed interface",
    durationSeconds: null,
    type: "Social distribution proof",
    whatItProves: "A native post and draft package exist; it does not prove external publication.",
    sourceAsset: null,
    outputAsset: null,
    proofStatus: "not-public-proof",
    fallbackAsset: "/images/platform/dashboard-ambient.webp",
    livePath: "/images/platform/dashboard-ambient.webp",
    workingStatus: "review-required",
  },
  ownedMediaLibrary: {
    assetId: "owner-media-library",
    sourceSystem: "CreatorVault media assets",
    creatorOwner: "CreatorVault owner ID 6",
    publicSafeStatus: "excluded",
    consentUsageStatus: "Creator-owned records were located, but their stored public URLs currently resolve to the app shell rather than media bytes and no public-display consent record is attached.",
    mediaKind: "motion",
    mobileSafe: false,
    desktopSafe: false,
    resolution: "Mixed",
    durationSeconds: null,
    type: "Private saved creator videos",
    whatItProves: "Existing creator-owned media exists in the library, but is not cleared or technically available for public showcase placement.",
    sourceAsset: null,
    outputAsset: null,
    proofStatus: "not-public-proof",
    fallbackAsset: "/images/platform/dashboard-empty-state.webp",
    livePath: "",
    workingStatus: "excluded",
  },
};

export const HOMEPAGE_MEDIA_SEQUENCE = [
  HOMEPAGE_MEDIA.kingcamHero,
  HOMEPAGE_MEDIA.womenCreatorMotion,
  HOMEPAGE_MEDIA.womenCreatorAudienceMotion,
  HOMEPAGE_MEDIA.vaultxRevenueVisual,
  HOMEPAGE_MEDIA.vaultxTrailer,
  HOMEPAGE_MEDIA.kingcamCampaignSource,
  HOMEPAGE_MEDIA.kingcamPlatformTrailer,
  HOMEPAGE_MEDIA.premiumUnlockVisual,
  HOMEPAGE_MEDIA.creationArsenal,
] as const;

export const MEDIA_FALLBACKS = {
  kingcamHero: HOMEPAGE_MEDIA.kingcamHero.fallbackAsset,
  womenCreatorMotion: HOMEPAGE_MEDIA.womenCreatorMotion.fallbackAsset,
  womenCreatorAudienceMotion: HOMEPAGE_MEDIA.womenCreatorAudienceMotion.fallbackAsset,
  vaultxRevenueVisual: HOMEPAGE_MEDIA.vaultxRevenueVisual.fallbackAsset,
  vaultxTrailer: HOMEPAGE_MEDIA.vaultxTrailer.fallbackAsset,
  kingcamCampaignSource: HOMEPAGE_MEDIA.kingcamCampaignSource.fallbackAsset,
  kingcamPlatformTrailer: HOMEPAGE_MEDIA.kingcamPlatformTrailer.fallbackAsset,
  premiumUnlockVisual: HOMEPAGE_MEDIA.premiumUnlockVisual.fallbackAsset,
} as const;
