export type PublicMediaStatus = "approved" | "review-required" | "excluded";
export type ProofStatus = "watchable-platform-visual" | "watchable-style-reference" | "unverified-result" | "not-public-proof";
export type PublicProofEligibility = "legacy_verified_campaign" | "owner_certified_public_proof" | "not_eligible";

export type HomepageMediaAsset = {
  assetId: string;
  sourceSystem: string;
  creatorOwner: string;
  publicSafeStatus: PublicMediaStatus;
  consentUsageStatus: string;
  mediaKind: "motion" | "static";
  mobileSafe: boolean;
  desktopSafe: boolean;
  resolution: string;
  durationSeconds: number | null;
  type: string;
  whatItProves: string;
  sourceAsset: string | null;
  outputAsset: string | null;
  proofStatus: ProofStatus;
  publicProofEligibility?: PublicProofEligibility;
  fallbackAsset: string;
  livePath: string;
  workingStatus: "ready" | "review-required" | "excluded";
};

/**
 * Canonical public/showcase media registry.
 *
 * Assets are public-facing only when their repository provenance documents that
 * intent or their owning product record is already public. This registry never
 * upgrades a style reference into a creator-result claim.
 */
export const HOMEPAGE_MEDIA: Record<string, HomepageMediaAsset> = {
  kingcamHero: {
    assetId: "kingcam-hero-cam",
    publicProofEligibility: "legacy_verified_campaign",
    sourceSystem: "KingCam clone campaign",
    creatorOwner: "KingCam / CreatorVault",
    publicSafeStatus: "approved",
    consentUsageStatus: "CreatorVault-owned public campaign asset; tracked in the VaultX trailer provenance record.",
    mediaKind: "motion",
    mobileSafe: true,
    desktopSafe: true,
    resolution: "1080x1920",
    durationSeconds: 5.042,
    type: "Founder identity motion",
    whatItProves: "KingCam is the face of CreatorVault.",
    sourceAsset: "/uploads/vaultx/homepage-trailer/platform_native_pollo_kling3_latest.mp4",
    outputAsset: "/videos/vaultx-homepage-kingcam-trailer.mp4",
    proofStatus: "watchable-platform-visual",
    fallbackAsset: "/assets/kingcam-hero.jpg",
    livePath: "/videos/kingcam-hero-cam.mp4",
    workingStatus: "ready",
  },
  womenCreatorMotion: {
    assetId: "platform-dashboard-hero",
    publicProofEligibility: "legacy_verified_campaign",
    sourceSystem: "CreatorVault platform hero library",
    creatorOwner: "CreatorVault",
    publicSafeStatus: "approved",
    consentUsageStatus: "Added in the repository’s approved four-page hero-media release.",
    mediaKind: "motion",
    mobileSafe: true,
    desktopSafe: true,
    resolution: "704x1248",
    durationSeconds: 5.042,
    type: "Creator-at-work motion",
    whatItProves: "A woman creator is visibly operating her business.",
    sourceAsset: null,
    outputAsset: "/videos/platform/dashboard-hero.mp4",
    proofStatus: "watchable-platform-visual",
    fallbackAsset: "/images/vaultx/vaultx-business-presenter-mobile.png",
    livePath: "/videos/platform/dashboard-hero.mp4",
    workingStatus: "ready",
  },
  womenCreatorAudienceMotion: {
    assetId: "platform-marketplace-hero",
    publicProofEligibility: "legacy_verified_campaign",
    sourceSystem: "CreatorVault platform hero library",
    creatorOwner: "CreatorVault",
    publicSafeStatus: "approved",
    consentUsageStatus: "Existing public platform hero asset; its repository history documents dedicated public-route deployment.",
    mediaKind: "motion",
    mobileSafe: true,
    desktopSafe: true,
    resolution: "704x1248",
    durationSeconds: 5.042,
    type: "Creator-and-audience motion",
    whatItProves: "Creator content and fan attention belong in the same experience.",
    sourceAsset: null,
    outputAsset: "/videos/platform/marketplace-hero.mp4",
    proofStatus: "watchable-platform-visual",
    fallbackAsset: "/images/vaultx/vaultx-business-presenter-hero.png",
    livePath: "/videos/platform/marketplace-hero.mp4",
    workingStatus: "ready",
  },
  luxuryGoldRoomDemoSource: {
    assetId: "creatorvault-demo-luxury-gold-room-1080",
    sourceSystem: "CreatorVault-owned approved demonstration source",
    creatorOwner: "CreatorVault",
    publicSafeStatus: "approved",
    consentUsageStatus: "First-party generated demonstration source, imported as approved_demo and verified with source evidence c9dab05c-8296-495d-b6a7-80d79c32e0b9.",
    mediaKind: "motion",
    mobileSafe: true,
    desktopSafe: true,
    resolution: "1080x1920",
    durationSeconds: 8,
    type: "CreatorVault-owned editorial demonstration",
    whatItProves: "A clearly classified first-party visual reference is available; it is not presented as a creator upload or Body Cinema result.",
    sourceAsset: "https://creatorvault.live/uploads/content-vault/7999b534-ca99-4376-8705-19f087b32b6b/CreatorVault-Demo-Source--Luxury-Gold-Room-1080.mp4",
    outputAsset: null,
    proofStatus: "watchable-style-reference",
    fallbackAsset: "/images/home/luxury-gold-room-demo-poster.jpg",
    livePath: "https://creatorvault.live/uploads/content-vault/7999b534-ca99-4376-8705-19f087b32b6b/CreatorVault-Demo-Source--Luxury-Gold-Room-1080.mp4",
    workingStatus: "ready",
  },
  bodyCinemaConcept: {
    assetId: "body-cinema-transformation-reference",
    sourceSystem: "Body Cinema visual library",
    creatorOwner: "CreatorVault",
    publicSafeStatus: "review-required",
    consentUsageStatus: "Repository asset is public-facing, but creator/model usage clearance is not embedded with the file.",
    mediaKind: "motion",
    mobileSafe: true,
    desktopSafe: true,
    resolution: "720x1280",
    durationSeconds: 4.01,
    type: "Before-and-after creative reference",
    whatItProves: "A cinematic transformation visual exists; it does not prove a creator-specific Body Cinema result.",
    sourceAsset: null,
    outputAsset: "/assets/hero-transformation.mp4",
    proofStatus: "unverified-result",
    fallbackAsset: "/images/platform/body-cinema-feature-proof.webp",
    livePath: "/assets/hero-transformation.mp4",
    workingStatus: "review-required",
  },
  bodyCinemaIntelligenceReference: {
    assetId: "body-cinema-intelligence-reference",
    sourceSystem: "Body Cinema visual library",
    creatorOwner: "CreatorVault",
    publicSafeStatus: "review-required",
    consentUsageStatus: "Repository asset is public-facing, but creator/model usage clearance is not embedded with the file.",
    mediaKind: "motion",
    mobileSafe: true,
    desktopSafe: true,
    resolution: "720x1280",
    durationSeconds: 4.01,
    type: "Intelligence visual reference",
    whatItProves: "The product’s intended analysis language, not analysis of a public creator source.",
    sourceAsset: null,
    outputAsset: "/assets/intelligence-overlay.mp4",
    proofStatus: "unverified-result",
    fallbackAsset: "/images/platform/body-cinema-hero.webp",
    livePath: "/assets/intelligence-overlay.mp4",
    workingStatus: "review-required",
  },
  vaultxRevenueVisual: {
    assetId: "vaultx-hero",
    publicProofEligibility: "legacy_verified_campaign",
    sourceSystem: "VaultX public product visual",
    creatorOwner: "CreatorVault",
    publicSafeStatus: "approved",
    consentUsageStatus: "Existing deployed VaultX public product asset.",
    mediaKind: "motion",
    mobileSafe: true,
    desktopSafe: true,
    resolution: "720x1280",
    durationSeconds: 4.75,
    type: "VaultX product visual",
    whatItProves: "VaultX is a visible premium content-and-revenue workspace.",
    sourceAsset: null,
    outputAsset: "/videos/platform/vaultx-hero.mp4",
    proofStatus: "watchable-platform-visual",
    fallbackAsset: "/images/platform/vaultx-hero.webp",
    livePath: "/videos/platform/vaultx-hero.mp4",
    workingStatus: "ready",
  },
  vaultxTrailer: {
    assetId: "vaultx-cinematic-trailer",
    publicProofEligibility: "legacy_verified_campaign",
    sourceSystem: "VaultX cinematic trailer",
    creatorOwner: "CreatorVault",
    publicSafeStatus: "approved",
    consentUsageStatus: "Repository public trailer asset with matching public poster.",
    mediaKind: "motion",
    mobileSafe: true,
    desktopSafe: true,
    resolution: "1280x720",
    durationSeconds: 28.778,
    type: "Product walkthrough motion",
    whatItProves: "VaultX product language and vertical-video workflow.",
    sourceAsset: null,
    outputAsset: "/videos/vaultx-cinematic-trailer.mp4",
    proofStatus: "watchable-platform-visual",
    fallbackAsset: "/videos/vaultx-cinematic-trailer-poster.png",
    livePath: "/videos/vaultx-cinematic-trailer.mp4",
    workingStatus: "ready",
  },
  kingcamCampaignSource: {
    assetId: "kingcam-platform-native-source",
    publicProofEligibility: "legacy_verified_campaign",
    sourceSystem: "CreatorVault native KingCam production",
    creatorOwner: "KingCam / CreatorVault",
    publicSafeStatus: "approved",
    consentUsageStatus: "Recorded as the CreatorVault-native source asset in the public trailer provenance record.",
    mediaKind: "motion",
    mobileSafe: true,
    desktopSafe: true,
    resolution: "1920x1080",
    durationSeconds: 5.042,
    type: "Campaign source motion",
    whatItProves: "A persisted platform-native source clip exists before the public founder trailer.",
    sourceAsset: null,
    outputAsset: "/videos/vaultx-homepage-kingcam-trailer.mp4",
    proofStatus: "watchable-platform-visual",
    fallbackAsset: "/videos/vaultx-homepage-kingcam-trailer-poster.jpg",
    livePath: "/uploads/vaultx/homepage-trailer/platform_native_pollo_kling3_latest.mp4",
    workingStatus: "ready",
  },
  kingcamPlatformTrailer: {
    assetId: "vaultx-homepage-kingcam-trailer",
    publicProofEligibility: "legacy_verified_campaign",
    sourceSystem: "CreatorVault native KingCam production",
    creatorOwner: "KingCam / CreatorVault",
    publicSafeStatus: "approved",
    consentUsageStatus: "Provenance file records CreatorVault-native production and intended public homepage output.",
    mediaKind: "motion",
    mobileSafe: true,
    desktopSafe: true,
    resolution: "1920x1080",
    durationSeconds: 18,
    type: "Founder and platform trailer",
    whatItProves: "CreatorVault has a persisted, platform-native motion trailer.",
    sourceAsset: "/uploads/vaultx/homepage-trailer/platform_native_pollo_kling3_latest.mp4",
    outputAsset: "/videos/vaultx-homepage-kingcam-trailer.mp4",
    proofStatus: "watchable-platform-visual",
    fallbackAsset: "/videos/vaultx-homepage-kingcam-trailer-poster.jpg",
    livePath: "/videos/vaultx-homepage-kingcam-trailer.mp4",
    workingStatus: "ready",
  },
  premiumUnlockVisual: {
    assetId: "vaultx-final-drop",
    publicProofEligibility: "legacy_verified_campaign",
    sourceSystem: "VaultX visual library",
    creatorOwner: "CreatorVault",
    publicSafeStatus: "approved",
    consentUsageStatus: "Existing public project asset with no depicted creator or external personal data.",
    mediaKind: "motion",
    mobileSafe: true,
    desktopSafe: true,
    resolution: "720x1280",
    durationSeconds: 4.01,
    type: "Premium offer motion",
    whatItProves: "The visual mechanics of a premium unlock without claiming a completed sale or earnings amount.",
    sourceAsset: null,
    outputAsset: "/assets/final-drop.mp4",
    proofStatus: "watchable-platform-visual",
    fallbackAsset: "/images/platform/vaultx-feature-ppv.webp",
    livePath: "/assets/final-drop.mp4",
    workingStatus: "ready",
  },
  kingcamHeroLoopProof: {
    assetId: "b99b8561-1d34-4799-aa3d-9f95c8ff5136",
    sourceSystem: "CreatorVault Assembly lane",
    creatorOwner: "KingCam / CreatorVault",
    publicSafeStatus: "excluded",
    consentUsageStatus: "Approved CreatorVault demonstration identity asset with durable accepted-master lineage.",
    mediaKind: "motion",
    mobileSafe: true,
    desktopSafe: true,
    resolution: "1080x1920",
    durationSeconds: 6.037,
    type: "KingCam homepage hero loop",
    whatItProves: "A real accepted KingCam derivative can play full-body in a public CreatorVault hero treatment.",
    sourceAsset: "128de5ea-a6bf-4cb8-a859-6472187a7b50",
    outputAsset: "b99b8561-1d34-4799-aa3d-9f95c8ff5136",
    proofStatus: "watchable-platform-visual",
    fallbackAsset: "/assets/kingcam-hero.jpg",
    livePath: "https://creatorvault.live/uploads/renders/2a16695b-fd71-40b8-95ed-92f3de6755eb/vaultx-edit-2a16695b-fd71-40b8-95ed-92f3de6755eb.mp4",
    workingStatus: "ready",
  },
  kingcamTrailerProof: {
    assetId: "128de5ea-a6bf-4cb8-a859-6472187a7b50",
    sourceSystem: "CreatorVault Trailer Maker / Assembly lane",
    creatorOwner: "KingCam / CreatorVault",
    publicSafeStatus: "excluded",
    consentUsageStatus: "Approved CreatorVault demonstration identity asset with inspected trailer lineage.",
    mediaKind: "motion",
    mobileSafe: true,
    desktopSafe: true,
    resolution: "1080x1920",
    durationSeconds: 6.133,
    type: "KingCam campaign trailer",
    whatItProves: "Trailer Maker can assemble an accepted source into a watchable three-beat KingCam short-form trailer.",
    sourceAsset: "b5beb74f-3839-413f-ab0d-2884dddd5e27",
    outputAsset: "128de5ea-a6bf-4cb8-a859-6472187a7b50",
    proofStatus: "watchable-platform-visual",
    fallbackAsset: "/assets/kingcam-hero.jpg",
    livePath: "https://creatorvault.live/uploads/renders/f729fe42-3373-44f3-80a8-a26e8337b0ac/vaultx-edit-f729fe42-3373-44f3-80a8-a26e8337b0ac.mp4",
    workingStatus: "ready",
  },
  bodyCinemaArchStrictShowcase: {
    assetId: "7240f27f-6e92-4fc2-8026-66b7d86168e4",
    sourceSystem: "Body Cinema / source-preserving Assembly lane",
    creatorOwner: "CreatorVault-owned approved demonstration source",
    publicSafeStatus: "excluded",
    consentUsageStatus: "Excluded from public proof: the cosmetic treatment result is retained only as internal historical evidence.",
    mediaKind: "motion",
    mobileSafe: true,
    desktopSafe: true,
    resolution: "1080x1920",
    durationSeconds: 5.507,
    type: "Body Cinema — The Arch / Sculpture House",
    whatItProves: "Excluded from public proof: cosmetic treatment variation is not a flagship CreatorVault creation.",
    sourceAsset: "bd4577fa-1511-4bff-b598-f1cf515ddca3",
    outputAsset: "7240f27f-6e92-4fc2-8026-66b7d86168e4",
    proofStatus: "not-public-proof",
    fallbackAsset: "",
    livePath: "https://creatorvault.live/uploads/renders/217aa25a-13c3-4b79-a8da-9fb2f4287851/vaultx-edit-217aa25a-13c3-4b79-a8da-9fb2f4287851.mp4",
    workingStatus: "excluded",
  },
  bodyCinemaArchProof: {
    assetId: "bc6842b1-b774-4957-8d75-a871250a6b41",
    sourceSystem: "Body Cinema / Assembly lane",
    creatorOwner: "CreatorVault approved demonstration source",
    publicSafeStatus: "excluded",
    consentUsageStatus: "Approved CreatorVault demonstration source and accepted Body Cinema master.",
    mediaKind: "motion",
    mobileSafe: true,
    desktopSafe: true,
    resolution: "720x1280",
    durationSeconds: 3.2,
    type: "Body Cinema — The Arch",
    whatItProves: "A real approved source was turned into an accepted Body Cinema treatment with distinct body-line direction.",
    sourceAsset: "769cd88e-6d30-456a-bdbc-8eccf3641541",
    outputAsset: "bc6842b1-b774-4957-8d75-a871250a6b41",
    proofStatus: "watchable-platform-visual",
    fallbackAsset: "/images/platform/body-cinema-feature-proof.webp",
    livePath: "https://creatorvault.live/uploads/renders/138a4925-d295-4430-bd3c-14f45f26e5db/vaultx-edit-138a4925-d295-4430-bd3c-14f45f26e5db.mp4",
    workingStatus: "ready",
  },
  bodyCinemaSilhouetteProof: {
    assetId: "98aee65d-a71c-42d4-a64e-d21250834b6f",
    sourceSystem: "Body Cinema / Assembly lane",
    creatorOwner: "CreatorVault approved demonstration source",
    publicSafeStatus: "excluded",
    consentUsageStatus: "Approved CreatorVault demonstration source and accepted Body Cinema master.",
    mediaKind: "motion",
    mobileSafe: true,
    desktopSafe: true,
    resolution: "720x1280",
    durationSeconds: 3.2,
    type: "Body Cinema — Silhouette",
    whatItProves: "The same real source can receive a materially different silhouette-and-light treatment.",
    sourceAsset: "769cd88e-6d30-456a-bdbc-8eccf3641541",
    outputAsset: "98aee65d-a71c-42d4-a64e-d21250834b6f",
    proofStatus: "watchable-platform-visual",
    fallbackAsset: "/images/platform/body-cinema-feature-proof.webp",
    livePath: "https://creatorvault.live/uploads/renders/3fd673b4-9d4d-487c-b74e-2e2786318fc1/vaultx-edit-3fd673b4-9d4d-487c-b74e-2e2786318fc1.mp4",
    workingStatus: "ready",
  },
  bodyCinemaLuxuryProof: {
    assetId: "158f18dc-db9e-4091-9746-a69a6dbdca96",
    sourceSystem: "Body Cinema / Assembly lane",
    creatorOwner: "CreatorVault approved demonstration source",
    publicSafeStatus: "excluded",
    consentUsageStatus: "Approved CreatorVault demonstration source and accepted Body Cinema master.",
    mediaKind: "motion",
    mobileSafe: true,
    desktopSafe: true,
    resolution: "720x1280",
    durationSeconds: 3.2,
    type: "Body Cinema — Luxury Reveal",
    whatItProves: "The same real source can receive a detail-led luxury campaign treatment.",
    sourceAsset: "769cd88e-6d30-456a-bdbc-8eccf3641541",
    outputAsset: "158f18dc-db9e-4091-9746-a69a6dbdca96",
    proofStatus: "watchable-platform-visual",
    fallbackAsset: "/images/platform/body-cinema-feature-proof.webp",
    livePath: "https://creatorvault.live/uploads/renders/c2c564d5-96cc-4fa9-aeac-893980769025/vaultx-edit-c2c564d5-96cc-4fa9-aeac-893980769025.mp4",
    workingStatus: "ready",
  },
  bodyCinemaVipProof: {
    assetId: "768b5648-c298-4a99-999d-07caeb062929",
    sourceSystem: "Body Cinema / Assembly lane",
    creatorOwner: "CreatorVault approved demonstration source",
    publicSafeStatus: "excluded",
    consentUsageStatus: "Approved CreatorVault demonstration source and accepted Body Cinema master.",
    mediaKind: "motion",
    mobileSafe: true,
    desktopSafe: true,
    resolution: "720x1280",
    durationSeconds: 3.2,
    type: "Body Cinema — VIP Tease",
    whatItProves: "The same real source can receive an access-hook rhythm distinct from its cinematic treatments.",
    sourceAsset: "769cd88e-6d30-456a-bdbc-8eccf3641541",
    outputAsset: "768b5648-c298-4a99-999d-07caeb062929",
    proofStatus: "watchable-platform-visual",
    fallbackAsset: "/images/platform/body-cinema-feature-proof.webp",
    livePath: "https://creatorvault.live/uploads/renders/a27a2ea5-8695-42a7-bd45-a4a749289eb9/vaultx-edit-a27a2ea5-8695-42a7-bd45-a4a749289eb9.mp4",
    workingStatus: "ready",
  },
  bodyCinemaArchTeaserProof: {
    assetId: "9d701191-abee-4071-a676-588241937a66",
    sourceSystem: "Body Cinema / Assembly lane",
    creatorOwner: "CreatorVault approved demonstration source",
    publicSafeStatus: "excluded",
    consentUsageStatus: "Approved CreatorVault demonstration source and accepted derivative lineage.",
    mediaKind: "motion",
    mobileSafe: true,
    desktopSafe: true,
    resolution: "1080x1920",
    durationSeconds: 3.2,
    type: "VaultX — The Arch Social Teaser",
    whatItProves: "An accepted Body Cinema master can create a ready-to-use social teaser while retaining its parent-master lineage.",
    sourceAsset: "bc6842b1-b774-4957-8d75-a871250a6b41",
    outputAsset: "9d701191-abee-4071-a676-588241937a66",
    proofStatus: "watchable-platform-visual",
    fallbackAsset: "/images/platform/body-cinema-feature-proof.webp",
    livePath: "https://creatorvault.live/uploads/renders/559b02e6-996e-4f5e-932c-d6d780e05d4d/vaultx-edit-559b02e6-996e-4f5e-932c-d6d780e05d4d.mp4",
    workingStatus: "ready",
  },
  creationArsenal: {
    assetId: "creatorvault-reel-arsenal",
    sourceSystem: "CreatorVault reel library",
    creatorOwner: "CreatorVault",
    publicSafeStatus: "approved",
    consentUsageStatus: "Existing public project assets showing CreatorVault creative outputs.",
    mediaKind: "static",
    mobileSafe: true,
    desktopSafe: true,
    resolution: "Assorted output canvases",
    durationSeconds: null,
    type: "Creation output collection",
    whatItProves: "The platform represents multiple creation categories without inventing a result or revenue claim.",
    sourceAsset: null,
    outputAsset: null,
    proofStatus: "watchable-platform-visual",
    fallbackAsset: "/images/reel/reel-cinematic-trailer.png",
    livePath: "/images/reel/reel-cinematic-trailer.png",
    workingStatus: "ready",
  },
  socialVisual: {
    assetId: "creatorvault-native-social-record",
    sourceSystem: "Canonical Social Empire",
    creatorOwner: "KingCam / CreatorVault",
    publicSafeStatus: "review-required",
    consentUsageStatus: "A real native post and approval-gated external drafts exist, but no public screenshot or public media output has a verified serving path in this release.",
    mediaKind: "static",
    mobileSafe: true,
    desktopSafe: true,
    resolution: "Record-backed interface",
    durationSeconds: null,
    type: "Social distribution proof",
    whatItProves: "A native post and draft package exist; it does not prove external publication.",
    sourceAsset: null,
    outputAsset: null,
    proofStatus: "not-public-proof",
    fallbackAsset: "/images/platform/dashboard-ambient.webp",
    livePath: "/images/platform/dashboard-ambient.webp",
    workingStatus: "review-required",
  },
  ownedMediaLibrary: {
    assetId: "owner-media-library",
    sourceSystem: "CreatorVault media assets",
    creatorOwner: "CreatorVault owner ID 6",
    publicSafeStatus: "excluded",
    consentUsageStatus: "Creator-owned records were located, but their stored public URLs currently resolve to the app shell rather than media bytes and no public-display consent record is attached.",
    mediaKind: "motion",
    mobileSafe: false,
    desktopSafe: false,
    resolution: "Mixed",
    durationSeconds: null,
    type: "Private saved creator videos",
    whatItProves: "Existing creator-owned media exists in the library, but is not cleared or technically available for public showcase placement.",
    sourceAsset: null,
    outputAsset: null,
    proofStatus: "not-public-proof",
    fallbackAsset: "/images/platform/dashboard-empty-state.webp",
    livePath: "",
    workingStatus: "excluded",
  },
};

// Public media may not include historic Assembly/Body Cinema outputs that relied on
// the now-prohibited FFmpeg creative-effect path. They remain internal evidence only.
export function isPublicHomepageEligible(asset: HomepageMediaAsset): boolean {
  return asset.publicSafeStatus === "approved"
    && asset.workingStatus === "ready"
    && asset.mediaKind === "motion"
    && (asset.publicProofEligibility === "legacy_verified_campaign" || asset.publicProofEligibility === "owner_certified_public_proof");
}

export const HOMEPAGE_MEDIA_SEQUENCE = [
  HOMEPAGE_MEDIA.kingcamHero,
  HOMEPAGE_MEDIA.womenCreatorMotion,
  HOMEPAGE_MEDIA.womenCreatorAudienceMotion,
  HOMEPAGE_MEDIA.vaultxRevenueVisual,
  HOMEPAGE_MEDIA.vaultxTrailer,
  HOMEPAGE_MEDIA.kingcamCampaignSource,
  HOMEPAGE_MEDIA.kingcamPlatformTrailer,
  HOMEPAGE_MEDIA.premiumUnlockVisual,
].filter(isPublicHomepageEligible);

export const MEDIA_FALLBACKS = {
  kingcamHero: HOMEPAGE_MEDIA.kingcamHero.fallbackAsset,
  womenCreatorMotion: HOMEPAGE_MEDIA.womenCreatorMotion.fallbackAsset,
  womenCreatorAudienceMotion: HOMEPAGE_MEDIA.womenCreatorAudienceMotion.fallbackAsset,
  vaultxRevenueVisual: HOMEPAGE_MEDIA.vaultxRevenueVisual.fallbackAsset,
  vaultxTrailer: HOMEPAGE_MEDIA.vaultxTrailer.fallbackAsset,
  kingcamCampaignSource: HOMEPAGE_MEDIA.kingcamCampaignSource.fallbackAsset,
  kingcamPlatformTrailer: HOMEPAGE_MEDIA.kingcamPlatformTrailer.fallbackAsset,
  premiumUnlockVisual: HOMEPAGE_MEDIA.premiumUnlockVisual.fallbackAsset,
} as const;
