-- Add missing columns to marketplace_products table
ALTER TABLE marketplace_products 
ADD COLUMN IF NOT EXISTS category VARCHAR(100),
ADD COLUMN IF NOT EXISTS short_description VARCHAR(280),
ADD COLUMN IF NOT EXISTS main_image VARCHAR(500),
ADD COLUMN IF NOT EXISTS additional_images JSON,
ADD COLUMN IF NOT EXISTS product_video VARCHAR(500),
ADD COLUMN IF NOT EXISTS digital_files JSON,
ADD COLUMN IF NOT EXISTS download_limit INT,
ADD COLUMN IF NOT EXISTS access_duration INT,
ADD COLUMN IF NOT EXISTS shipping_type ENUM('self', 'fulfillment'),
ADD COLUMN IF NOT EXISTS shipping_cost INT,
ADD COLUMN IF NOT EXISTS estimated_delivery_days INT,
ADD COLUMN IF NOT EXISTS inventory INT,
ADD COLUMN IF NOT EXISTS variations JSON,
ADD COLUMN IF NOT EXISTS service_duration INT,
ADD COLUMN IF NOT EXISTS delivery_methods JSON,
ADD COLUMN IF NOT EXISTS booking_enabled BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS turnaround_days INT,
ADD COLUMN IF NOT EXISTS regular_price INT,
ADD COLUMN IF NOT EXISTS sale_price INT,
ADD COLUMN IF NOT EXISTS sale_end_date TIMESTAMP,
ADD COLUMN IF NOT EXISTS monthly_price INT,
ADD COLUMN IF NOT EXISTS keywords JSON,
ADD COLUMN IF NOT EXISTS target_audience JSON,
ADD COLUMN IF NOT EXISTS content_rating ENUM('general', '18+', '21+') DEFAULT 'general',
ADD COLUMN IF NOT EXISTS refund_policy ENUM('no-refunds', '7-day', '30-day', 'custom') DEFAULT 'no-refunds',
ADD COLUMN IF NOT EXISTS custom_refund_policy TEXT,
ADD COLUMN IF NOT EXISTS customer_instructions TEXT,
ADD COLUMN IF NOT EXISTS terms_of_use TEXT,
ADD COLUMN IF NOT EXISTS published_at TIMESTAMP,
ADD COLUMN IF NOT EXISTS scheduled_for TIMESTAMP,
ADD COLUMN IF NOT EXISTS view_count INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS sales_count INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_revenue INT DEFAULT 0;
