CREATE TABLE IF NOT EXISTS `recruiter_creator_profiles` (
  `id` int AUTO_INCREMENT NOT NULL,
  `platform` varchar(40) NOT NULL,
  `handle` varchar(160) NOT NULL,
  `display_name` varchar(255),
  `profile_url` text,
  `source` varchar(80) NOT NULL DEFAULT 'manual',
  `bio` text,
  `niche` varchar(180),
  `followers` int NOT NULL DEFAULT 0,
  `engagement_rate` decimal(5,2) NOT NULL DEFAULT '0.00',
  `recent_post` text,
  `platforms` json NOT NULL,
  `monetization_score` int NOT NULL DEFAULT 0,
  `fit_score` int NOT NULL DEFAULT 0,
  `urgency_score` int NOT NULL DEFAULT 0,
  `total_score` int NOT NULL DEFAULT 0,
  `score_breakdown` json NOT NULL,
  `audit_preview` json NOT NULL,
  `trailer_concept` text,
  `outreach_message` text,
  `onboarding_url` text,
  `telegram_username` varchar(160),
  `telegram_ready` boolean NOT NULL DEFAULT false,
  `stripe_link_status` varchar(40) NOT NULL DEFAULT 'not_started',
  `status` enum('new','qualified','queued','contacted','replied','onboarding','onboarded','declined') NOT NULL DEFAULT 'new',
  `priority` enum('low','medium','high','critical') NOT NULL DEFAULT 'medium',
  `last_contacted_at` timestamp NULL,
  `onboarded_at` timestamp NULL,
  `metadata` json,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `recruiter_creator_profiles_id` PRIMARY KEY(`id`),
  CONSTRAINT `uniq_recruiter_creator_profiles_platform_handle` UNIQUE(`platform`, `handle`),
  KEY `idx_recruiter_creator_profiles_total_score` (`total_score`),
  KEY `idx_recruiter_creator_profiles_status` (`status`),
  KEY `idx_recruiter_creator_profiles_priority` (`priority`),
  KEY `idx_recruiter_creator_profiles_source` (`source`)
);
