-- CreatorVault Activation War Room
-- Money-first operator system for activation, first-dollar outcomes, renewals, payouts, blockers, and ledger-backed cashflow.

CREATE TABLE IF NOT EXISTS activation_war_room_snapshots (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  snapshot_date DATE NOT NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'active',
  ledger_cash_collected_cents BIGINT NOT NULL DEFAULT 0,
  ledger_creator_earnings_cents BIGINT NOT NULL DEFAULT 0,
  ledger_platform_share_cents BIGINT NOT NULL DEFAULT 0,
  completed_transaction_count INT NOT NULL DEFAULT 0,
  active_subscription_count INT NOT NULL DEFAULT 0,
  active_mrr_cents BIGINT NOT NULL DEFAULT 0,
  first_dollar_creator_count INT NOT NULL DEFAULT 0,
  activation_target_count INT NOT NULL DEFAULT 0,
  activated_creator_count INT NOT NULL DEFAULT 0,
  payout_pending_cents BIGINT NOT NULL DEFAULT 0,
  payout_completed_cents BIGINT NOT NULL DEFAULT 0,
  blocker_open_count INT NOT NULL DEFAULT 0,
  urgent_intervention_count INT NOT NULL DEFAULT 0,
  automated_outreach_sent BOOLEAN NOT NULL DEFAULT FALSE,
  projections_included BOOLEAN NOT NULL DEFAULT FALSE,
  synthetic_metrics_included BOOLEAN NOT NULL DEFAULT FALSE,
  revenue_is_ledger_backed BOOLEAN NOT NULL DEFAULT TRUE,
  source_tables JSON NOT NULL,
  proof_payload JSON NULL,
  computed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_activation_war_room_snapshot_date (snapshot_date),
  KEY idx_activation_war_room_snapshot_status_date (status, snapshot_date),
  KEY idx_activation_war_room_snapshot_computed (computed_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS activation_war_room_creator_status (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  snapshot_date DATE NOT NULL,
  profile_id INT NULL,
  creator_id BIGINT NULL,
  pipeline_id BIGINT UNSIGNED NULL,
  conversion_packet_id INT NULL,
  handle VARCHAR(180) NOT NULL,
  platform VARCHAR(80) NOT NULL DEFAULT 'unknown',
  display_name VARCHAR(255) NULL,
  activation_stage VARCHAR(80) NOT NULL DEFAULT 'targeted',
  activation_status VARCHAR(80) NOT NULL DEFAULT 'not_started',
  checkout_status VARCHAR(80) NOT NULL DEFAULT 'not_started',
  renewal_status VARCHAR(80) NOT NULL DEFAULT 'unknown',
  payout_status VARCHAR(80) NOT NULL DEFAULT 'unknown',
  first_dollar_status VARCHAR(80) NOT NULL DEFAULT 'not_earned',
  first_completed_transaction_id BIGINT NULL,
  ledger_cash_collected_cents BIGINT NOT NULL DEFAULT 0,
  active_subscription_count INT NOT NULL DEFAULT 0,
  active_mrr_cents BIGINT NOT NULL DEFAULT 0,
  available_balance_cents BIGINT NOT NULL DEFAULT 0,
  pending_balance_cents BIGINT NOT NULL DEFAULT 0,
  priority_score INT NOT NULL DEFAULT 0,
  priority_band VARCHAR(40) NOT NULL DEFAULT 'medium',
  blocker_count INT NOT NULL DEFAULT 0,
  next_money_action VARCHAR(255) NOT NULL,
  intervention_priority INT NOT NULL DEFAULT 0,
  source_tables JSON NOT NULL,
  evidence_payload JSON NULL,
  revenue_is_ledger_backed BOOLEAN NOT NULL DEFAULT TRUE,
  projections_included BOOLEAN NOT NULL DEFAULT FALSE,
  synthetic_metrics_included BOOLEAN NOT NULL DEFAULT FALSE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_activation_war_room_status_date_profile (snapshot_date, profile_id),
  KEY idx_activation_war_room_status_priority (snapshot_date, intervention_priority),
  KEY idx_activation_war_room_status_handle (handle, platform),
  KEY idx_activation_war_room_status_creator (creator_id),
  KEY idx_activation_war_room_status_pipeline (pipeline_id),
  KEY idx_activation_war_room_status_first_tx (first_completed_transaction_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS activation_war_room_blockers (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  snapshot_date DATE NOT NULL,
  creator_status_id BIGINT UNSIGNED NULL,
  profile_id INT NULL,
  creator_id BIGINT NULL,
  pipeline_id BIGINT UNSIGNED NULL,
  blocker_key VARCHAR(120) NOT NULL,
  blocker_label VARCHAR(255) NOT NULL,
  severity VARCHAR(40) NOT NULL DEFAULT 'medium',
  blocker_status VARCHAR(40) NOT NULL DEFAULT 'open',
  next_resolution_action VARCHAR(255) NOT NULL,
  source_tables JSON NOT NULL,
  evidence_payload JSON NULL,
  resolution_note TEXT NULL,
  resolved_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_activation_war_room_blocker (snapshot_date, profile_id, blocker_key),
  KEY idx_activation_war_room_blocker_status (blocker_status, severity),
  KEY idx_activation_war_room_blocker_profile (profile_id),
  KEY idx_activation_war_room_blocker_creator_status (creator_status_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS activation_war_room_interventions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  snapshot_date DATE NOT NULL,
  creator_status_id BIGINT UNSIGNED NULL,
  profile_id INT NULL,
  creator_id BIGINT NULL,
  pipeline_id BIGINT UNSIGNED NULL,
  intervention_key VARCHAR(120) NOT NULL,
  intervention_type VARCHAR(80) NOT NULL DEFAULT 'operator_review',
  priority_score INT NOT NULL DEFAULT 0,
  priority_band VARCHAR(40) NOT NULL DEFAULT 'medium',
  next_money_action VARCHAR(255) NOT NULL,
  review_status VARCHAR(40) NOT NULL DEFAULT 'queued',
  automated_outreach_sent BOOLEAN NOT NULL DEFAULT FALSE,
  operator_note TEXT NULL,
  source_tables JSON NOT NULL,
  evidence_payload JSON NULL,
  reviewed_at DATETIME NULL,
  resolved_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_activation_war_room_intervention (snapshot_date, profile_id, intervention_key),
  KEY idx_activation_war_room_intervention_queue (review_status, priority_score),
  KEY idx_activation_war_room_intervention_profile (profile_id),
  KEY idx_activation_war_room_intervention_creator_status (creator_status_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
