-- Idempotent CreatorVault Top 5 Activation Sprint seed
-- Generated from /home/ubuntu/creatorvault_top5_selected_creators.json
-- Sprint date: 2026-05-09
-- Real outcome fields are ledger-backed only; source projections remain separate.

INSERT INTO top5_activation_sprint (
  sprint_date,
  top5_rank,
  sprint_status,
  source_table,
  source_id,
  profile_id,
  creator_id,
  pipeline_id,
  conversion_packet_id,
  handle,
  platform,
  display_name,
  niche,
  activation_score,
  priority_band,
  risk_level,
  approval_status,
  checkout_status,
  first_dollar_status,
  retention_status,
  payout_status,
  primary_blocker_key,
  primary_blocker_label,
  primary_blocker_severity,
  next_money_action,
  ledger_cash_collected_cents,
  completed_transaction_count,
  active_subscription_count,
  active_mrr_cents,
  available_balance_cents,
  pending_balance_cents,
  payout_request_count,
  projected_setup_revenue_cents,
  projected_mrr_cents,
  source_tables,
  selection_evidence_payload,
  ledger_evidence_payload,
  revenue_is_ledger_backed,
  projections_included,
  synthetic_metrics_included,
  automated_outreach_sent
) VALUES
  ('2026-05-09', 1, 'active', 'greatest_show_creators', '2', NULL, NULL, NULL, NULL, 'Princesa_De_Africa__greatest_show_creators_2', 'greatest_show', 'Princesa De Africa', 'lifestyle', 169, 'critical', 'low', 'requires_kingcam_approval', 'checkout_started', 'not_earned', 'not_active', 'not_applicable', 'checkout_started_but_no_completed_transaction', 'Checkout started but no completed transaction in ledger', 'critical', 'recover checkout with direct payment link and objection follow-up', 0, 0, 0, 0, 0, 0, 0, 400000, 275931, '["greatest_show_creators","daily_creator_pipeline","creator_conversion_packets","creator_checkout_automation_ledger","creator_acquisition_priorities","transactions","subscriptions","subscription_tiers","creator_balances","payout_requests"]', '{"generatedAt":"2026-05-09T13:55:23.687Z","selectionPolicy":"exactly five highest activationScore rows computed from verified production source rows plus ledger evidence; no synthetic revenue is counted","top5Rank":1,"sourceTable":"greatest_show_creators","sourceId":"2","sourceRowFound":true,"sourceHandle":"Princesa De Africa","sourceScore":89,"activationScore":169,"followers":6977,"engagementRate":3.73,"pipelineRows":2,"profileRows":2,"packetRows":2,"automationRows":2,"priorityRows":2,"checkoutStarts":2,"scoringReasons":["critical selected-target band","low operational risk","requires approval before outreach","high setup revenue projection from source packet","high projected MRR from source packet","audience-size signal in source row","engagement-rate signal in source row","VaultX/adult monetization fit","source row verified in production","daily pipeline evidence exists","conversion packet evidence exists","automation ledger evidence exists","acquisition priority evidence exists","checkout-start event evidence exists"]}', '{"realLedgerRevenueCents":0,"completedTransactions":0,"activeSubscriptions":0,"payoutRequests":0,"sourceTables":["transactions","subscriptions","subscription_tiers","creator_balances","payout_requests"]}', TRUE, FALSE, FALSE, FALSE),
  ('2026-05-09', 2, 'active', 'greatest_show_creators', '4', NULL, NULL, NULL, NULL, 'China_Marielka__greatest_show_creators_4', 'greatest_show', 'China (Marielka)', 'adult', 160, 'critical', 'low', 'requires_kingcam_approval', 'checkout_started', 'not_earned', 'not_active', 'not_applicable', 'checkout_started_but_no_completed_transaction', 'Checkout started but no completed transaction in ledger', 'critical', 'recover checkout with direct payment link and objection follow-up', 0, 0, 0, 0, 0, 0, 0, 400000, 59985, '["greatest_show_creators","daily_creator_pipeline","creator_conversion_packets","creator_checkout_automation_ledger","creator_acquisition_priorities","transactions","subscriptions","subscription_tiers","creator_balances","payout_requests"]', '{"generatedAt":"2026-05-09T13:55:23.687Z","selectionPolicy":"exactly five highest activationScore rows computed from verified production source rows plus ledger evidence; no synthetic revenue is counted","top5Rank":2,"sourceTable":"greatest_show_creators","sourceId":"4","sourceRowFound":true,"sourceHandle":"China (Marielka)","sourceScore":96,"activationScore":160,"followers":0,"engagementRate":0,"pipelineRows":1,"profileRows":1,"packetRows":1,"automationRows":1,"priorityRows":1,"checkoutStarts":1,"scoringReasons":["critical selected-target band","low operational risk","requires approval before outreach","high setup revenue projection from source packet","solid projected MRR from source packet","VaultX/adult monetization fit","source row verified in production","daily pipeline evidence exists","conversion packet evidence exists","automation ledger evidence exists","acquisition priority evidence exists","checkout-start event evidence exists"]}', '{"realLedgerRevenueCents":0,"completedTransactions":0,"activeSubscriptions":0,"payoutRequests":0,"sourceTables":["transactions","subscriptions","subscription_tiers","creator_balances","payout_requests"]}', TRUE, FALSE, FALSE, FALSE),
  ('2026-05-09', 3, 'active', 'greatest_show_creators', '7', NULL, NULL, NULL, NULL, 'Leslie_Princesa_De_Africa__greatest_show_creators_7', 'greatest_show', 'Leslie (Princesa De Africa)', 'adult', 160, 'critical', 'low', 'requires_kingcam_approval', 'checkout_started', 'not_earned', 'not_active', 'not_applicable', 'checkout_started_but_no_completed_transaction', 'Checkout started but no completed transaction in ledger', 'critical', 'recover checkout with direct payment link and objection follow-up', 0, 0, 0, 0, 0, 0, 0, 400000, 59985, '["greatest_show_creators","daily_creator_pipeline","creator_conversion_packets","creator_checkout_automation_ledger","creator_acquisition_priorities","transactions","subscriptions","subscription_tiers","creator_balances","payout_requests"]', '{"generatedAt":"2026-05-09T13:55:23.687Z","selectionPolicy":"exactly five highest activationScore rows computed from verified production source rows plus ledger evidence; no synthetic revenue is counted","top5Rank":3,"sourceTable":"greatest_show_creators","sourceId":"7","sourceRowFound":true,"sourceHandle":"Leslie (Princesa De Africa)","sourceScore":96,"activationScore":160,"followers":0,"engagementRate":0,"pipelineRows":1,"profileRows":1,"packetRows":1,"automationRows":1,"priorityRows":1,"checkoutStarts":1,"scoringReasons":["critical selected-target band","low operational risk","requires approval before outreach","high setup revenue projection from source packet","solid projected MRR from source packet","VaultX/adult monetization fit","source row verified in production","daily pipeline evidence exists","conversion packet evidence exists","automation ledger evidence exists","acquisition priority evidence exists","checkout-start event evidence exists"]}', '{"realLedgerRevenueCents":0,"completedTransactions":0,"activeSubscriptions":0,"payoutRequests":0,"sourceTables":["transactions","subscriptions","subscription_tiers","creator_balances","payout_requests"]}', TRUE, FALSE, FALSE, FALSE),
  ('2026-05-09', 4, 'active', 'greatest_show_creators', '9', NULL, NULL, NULL, NULL, 'China__greatest_show_creators_9', 'greatest_show', 'China', 'adult', 158, 'critical', 'low', 'requires_kingcam_approval', 'checkout_started', 'not_earned', 'not_active', 'not_applicable', 'checkout_started_but_no_completed_transaction', 'Checkout started but no completed transaction in ledger', 'critical', 'recover checkout with direct payment link and objection follow-up', 0, 0, 0, 0, 0, 0, 0, 400000, 114000, '["greatest_show_creators","daily_creator_pipeline","creator_conversion_packets","creator_checkout_automation_ledger","creator_acquisition_priorities","transactions","subscriptions","subscription_tiers","creator_balances","payout_requests"]', '{"generatedAt":"2026-05-09T13:55:23.687Z","selectionPolicy":"exactly five highest activationScore rows computed from verified production source rows plus ledger evidence; no synthetic revenue is counted","top5Rank":4,"sourceTable":"greatest_show_creators","sourceId":"9","sourceRowFound":true,"sourceHandle":"China","sourceScore":86,"activationScore":158,"followers":3889,"engagementRate":0,"pipelineRows":2,"profileRows":2,"packetRows":2,"automationRows":2,"priorityRows":2,"checkoutStarts":2,"scoringReasons":["critical selected-target band","low operational risk","requires approval before outreach","high setup revenue projection from source packet","high projected MRR from source packet","audience-size signal in source row","VaultX/adult monetization fit","source row verified in production","daily pipeline evidence exists","conversion packet evidence exists","automation ledger evidence exists","acquisition priority evidence exists","checkout-start event evidence exists"]}', '{"realLedgerRevenueCents":0,"completedTransactions":0,"activeSubscriptions":0,"payoutRequests":0,"sourceTables":["transactions","subscriptions","subscription_tiers","creator_balances","payout_requests"]}', TRUE, FALSE, FALSE, FALSE),
  ('2026-05-09', 5, 'active', 'greatest_show_creators', '6', NULL, NULL, NULL, NULL, 'Lirys_Twin__greatest_show_creators_6', 'greatest_show', 'Lirys (Twin)', 'cooking', 144, 'critical', 'low', 'requires_kingcam_approval', 'checkout_started', 'not_earned', 'not_active', 'not_applicable', 'checkout_started_but_no_completed_transaction', 'Checkout started but no completed transaction in ledger', 'critical', 'recover checkout with direct payment link and objection follow-up', 0, 0, 0, 0, 0, 0, 0, 400000, 44985, '["greatest_show_creators","daily_creator_pipeline","creator_conversion_packets","creator_checkout_automation_ledger","creator_acquisition_priorities","transactions","subscriptions","subscription_tiers","creator_balances","payout_requests"]', '{"generatedAt":"2026-05-09T13:55:23.687Z","selectionPolicy":"exactly five highest activationScore rows computed from verified production source rows plus ledger evidence; no synthetic revenue is counted","top5Rank":5,"sourceTable":"greatest_show_creators","sourceId":"6","sourceRowFound":true,"sourceHandle":"Lirys (Twin)","sourceScore":90,"activationScore":144,"followers":0,"engagementRate":0,"pipelineRows":1,"profileRows":1,"packetRows":1,"automationRows":1,"priorityRows":1,"checkoutStarts":1,"scoringReasons":["critical selected-target band","low operational risk","requires approval before outreach","high setup revenue projection from source packet","source row verified in production","daily pipeline evidence exists","conversion packet evidence exists","automation ledger evidence exists","acquisition priority evidence exists","checkout-start event evidence exists"]}', '{"realLedgerRevenueCents":0,"completedTransactions":0,"activeSubscriptions":0,"payoutRequests":0,"sourceTables":["transactions","subscriptions","subscription_tiers","creator_balances","payout_requests"]}', TRUE, FALSE, FALSE, FALSE)
ON DUPLICATE KEY UPDATE
  sprint_status = VALUES(sprint_status),
  source_table = VALUES(source_table),
  source_id = VALUES(source_id),
  profile_id = VALUES(profile_id),
  creator_id = VALUES(creator_id),
  pipeline_id = VALUES(pipeline_id),
  conversion_packet_id = VALUES(conversion_packet_id),
  display_name = VALUES(display_name),
  niche = VALUES(niche),
  activation_score = VALUES(activation_score),
  priority_band = VALUES(priority_band),
  risk_level = VALUES(risk_level),
  approval_status = VALUES(approval_status),
  checkout_status = VALUES(checkout_status),
  first_dollar_status = VALUES(first_dollar_status),
  retention_status = VALUES(retention_status),
  payout_status = VALUES(payout_status),
  primary_blocker_key = VALUES(primary_blocker_key),
  primary_blocker_label = VALUES(primary_blocker_label),
  primary_blocker_severity = VALUES(primary_blocker_severity),
  next_money_action = VALUES(next_money_action),
  ledger_cash_collected_cents = VALUES(ledger_cash_collected_cents),
  completed_transaction_count = VALUES(completed_transaction_count),
  active_subscription_count = VALUES(active_subscription_count),
  active_mrr_cents = VALUES(active_mrr_cents),
  available_balance_cents = VALUES(available_balance_cents),
  pending_balance_cents = VALUES(pending_balance_cents),
  payout_request_count = VALUES(payout_request_count),
  projected_setup_revenue_cents = VALUES(projected_setup_revenue_cents),
  projected_mrr_cents = VALUES(projected_mrr_cents),
  source_tables = VALUES(source_tables),
  selection_evidence_payload = VALUES(selection_evidence_payload),
  ledger_evidence_payload = VALUES(ledger_evidence_payload),
  revenue_is_ledger_backed = TRUE,
  projections_included = FALSE,
  synthetic_metrics_included = FALSE,
  automated_outreach_sent = FALSE,
  updated_at = NOW();

-- Proof query: exactly five ranks, no synthetic outcome claims.
SELECT sprint_date, COUNT(*) AS selected_count, MIN(top5_rank) AS min_rank, MAX(top5_rank) AS max_rank,
       SUM(ledger_cash_collected_cents) AS ledger_cash_collected_cents,
       SUM(completed_transaction_count) AS completed_transaction_count,
       SUM(active_subscription_count) AS active_subscription_count,
       SUM(CASE WHEN revenue_is_ledger_backed = TRUE AND projections_included = FALSE AND synthetic_metrics_included = FALSE AND automated_outreach_sent = FALSE THEN 1 ELSE 0 END) AS truthful_rows
FROM top5_activation_sprint
WHERE sprint_date = '2026-05-09'
GROUP BY sprint_date;
