-- CreatorVault First-Dollar Recovery System
-- Stripe/session-backed abandoned checkout recovery and ledger-only first-dollar clocks.

CREATE TABLE IF NOT EXISTS first_dollar_recovery_queue (
  id INT AUTO_INCREMENT PRIMARY KEY,
  recovery_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  source_table VARCHAR(120) NOT NULL,
  source_id VARCHAR(120) NOT NULL,
  source_id_hash VARCHAR(128) NOT NULL,
  creator_id INT NULL,
  buyer_id INT NULL,
  offer_type VARCHAR(60) NOT NULL DEFAULT 'unknown',
  offer_id VARCHAR(120) NULL,
  offer_id_hash VARCHAR(128) NULL,
  offer_title VARCHAR(255) NULL,
  package_attempted VARCHAR(255) NULL,
  recurring_tier_attempted VARCHAR(255) NULL,
  vip_tier_attempted VARCHAR(255) NULL,
  checkout_value_cents INT NOT NULL DEFAULT 0,
  recurring_mrr_value_cents INT NOT NULL DEFAULT 0,
  vip_value_cents INT NOT NULL DEFAULT 0,
  ledger_recovered_cents INT NOT NULL DEFAULT 0,
  stripe_session_ref VARCHAR(128) NULL,
  stripe_payment_intent_ref VARCHAR(128) NULL,
  stripe_subscription_ref VARCHAR(128) NULL,
  stripe_customer_ref VARCHAR(128) NULL,
  checkout_status VARCHAR(80) NOT NULL DEFAULT 'abandoned',
  checkout_started_at TIMESTAMP NULL,
  checkout_updated_at TIMESTAMP NULL,
  stripe_session_age_hours INT NULL,
  incomplete_payment_age_hours INT NULL,
  creator_activation_stage VARCHAR(80) NULL,
  buyer_intent_level VARCHAR(40) NOT NULL DEFAULT 'unknown',
  recovery_priority_score INT NOT NULL DEFAULT 0,
  recovery_priority_band VARCHAR(30) NOT NULL DEFAULT 'low',
  objection_key VARCHAR(120) NOT NULL DEFAULT 'checkout_state_unknown_needs_operator_review',
  objection_summary TEXT NULL,
  friction_key VARCHAR(120) NOT NULL DEFAULT 'stale_checkout_no_completion',
  friction_summary TEXT NULL,
  next_best_money_action TEXT NOT NULL,
  operator_status VARCHAR(60) NOT NULL DEFAULT 'new',
  operator_note TEXT NULL,
  last_operator_action_at TIMESTAMP NULL,
  checkout_is_stripe_session_backed BOOLEAN NOT NULL DEFAULT TRUE,
  revenue_is_ledger_backed BOOLEAN NOT NULL DEFAULT TRUE,
  synthetic_metrics_included BOOLEAN NOT NULL DEFAULT FALSE,
  fake_urgency_included BOOLEAN NOT NULL DEFAULT FALSE,
  automated_outreach_sent BOOLEAN NOT NULL DEFAULT FALSE,
  evidence_json JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_first_dollar_recovery_source (source_table, source_id_hash),
  KEY idx_first_dollar_recovery_score (recovery_priority_band, recovery_priority_score),
  KEY idx_first_dollar_recovery_creator (creator_id, recovery_priority_score),
  KEY idx_first_dollar_recovery_buyer (buyer_id),
  KEY idx_first_dollar_recovery_status (operator_status, recovery_priority_band),
  KEY idx_first_dollar_recovery_checkout_age (stripe_session_age_hours, incomplete_payment_age_hours),
  CONSTRAINT chk_fdr_priority_score CHECK (recovery_priority_score BETWEEN 0 AND 100),
  CONSTRAINT chk_fdr_ledger_recovered_nonnegative CHECK (ledger_recovered_cents >= 0),
  CONSTRAINT chk_fdr_attempted_nonnegative CHECK (checkout_value_cents >= 0 AND recurring_mrr_value_cents >= 0 AND vip_value_cents >= 0),
  CONSTRAINT chk_fdr_no_fake_metrics CHECK (synthetic_metrics_included = FALSE AND fake_urgency_included = FALSE AND automated_outreach_sent = FALSE),
  CONSTRAINT chk_fdr_ledger_only CHECK (revenue_is_ledger_backed = TRUE),
  CONSTRAINT chk_fdr_checkout_backed CHECK (checkout_is_stripe_session_backed = TRUE)
);

CREATE TABLE IF NOT EXISTS first_dollar_creator_clocks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  creator_id INT NOT NULL,
  first_dollar_status VARCHAR(60) NOT NULL DEFAULT 'not_earned',
  first_dollar_proximity_score INT NOT NULL DEFAULT 0,
  onboarding_at TIMESTAMP NULL,
  first_login_at TIMESTAMP NULL,
  first_checkout_at TIMESTAMP NULL,
  first_content_upload_at TIMESTAMP NULL,
  first_offer_launch_at TIMESTAMP NULL,
  first_telegram_activation_at TIMESTAMP NULL,
  ledger_first_transaction_at TIMESTAMP NULL,
  ledger_first_transaction_cents INT NOT NULL DEFAULT 0,
  hours_since_onboarding INT NULL,
  hours_since_first_login INT NULL,
  hours_since_first_checkout INT NULL,
  hours_since_first_content_upload INT NULL,
  hours_since_first_offer_launch INT NULL,
  hours_since_first_telegram_activation INT NULL,
  closest_recovery_queue_id INT NULL,
  next_best_money_action TEXT NOT NULL,
  clock_evidence_json JSON NULL,
  revenue_is_ledger_backed BOOLEAN NOT NULL DEFAULT TRUE,
  synthetic_metrics_included BOOLEAN NOT NULL DEFAULT FALSE,
  fake_urgency_included BOOLEAN NOT NULL DEFAULT FALSE,
  automated_outreach_sent BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_first_dollar_creator_clock (creator_id),
  KEY idx_first_dollar_clock_status (first_dollar_status, first_dollar_proximity_score),
  KEY idx_first_dollar_clock_checkout (first_checkout_at),
  CONSTRAINT chk_fdc_proximity_score CHECK (first_dollar_proximity_score BETWEEN 0 AND 100),
  CONSTRAINT chk_fdc_ledger_cents_nonnegative CHECK (ledger_first_transaction_cents >= 0),
  CONSTRAINT chk_fdc_no_fake_metrics CHECK (synthetic_metrics_included = FALSE AND fake_urgency_included = FALSE AND automated_outreach_sent = FALSE),
  CONSTRAINT chk_fdc_ledger_only CHECK (revenue_is_ledger_backed = TRUE)
);
