-- Additive Task 2 migration. No historical media, payouts, or identities are rewritten.
CREATE TABLE `persona_vaults` (
  `id` varchar(36) NOT NULL,
  `user_id` int NOT NULL,
  `persona_name` varchar(120) NOT NULL,
  `avatar_base_url` text NOT NULL,
  `avatar_sha256` varchar(64) NOT NULL,
  `lora_model_id` varchar(191),
  `voice_profile_id` varchar(191),
  `trigger_token` varchar(48),
  `signature_wardrobes` json NOT NULL,
  `accessory_attributes` json NOT NULL,
  `version` int unsigned NOT NULL DEFAULT 1,
  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `persona_vault_owner_name_unique` (`user_id`,`persona_name`),
  UNIQUE KEY `persona_vault_id_owner_unique` (`id`,`user_id`),
  CONSTRAINT `persona_vault_user_fk` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `persona_vault_version_positive` CHECK (`version` > 0)
) ENGINE=InnoDB;
--> statement-breakpoint
CREATE TABLE `persona_assets` (
  `id` varchar(36) NOT NULL,
  `persona_id` varchar(36) NOT NULL,
  `user_id` int NOT NULL,
  `asset_type` enum('avatar_base','reference_image','wardrobe_reference','voice_reference','chain_end_frame') NOT NULL,
  `asset_url` text NOT NULL,
  `source_url` text NOT NULL,
  `source_media_asset_id` varchar(191) NOT NULL,
  `sha256` varchar(64) NOT NULL,
  `tags` json NOT NULL,
  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `persona_assets_owner_kind_idx` (`user_id`,`persona_id`,`asset_type`),
  CONSTRAINT `persona_assets_owner_fk` FOREIGN KEY (`persona_id`,`user_id`) REFERENCES `persona_vaults` (`id`,`user_id`) ON DELETE RESTRICT
) ENGINE=InnoDB;
--> statement-breakpoint
CREATE TABLE `video_generation_chains` (
  `id` varchar(36) NOT NULL,
  `user_id` int NOT NULL,
  `persona_id` varchar(36) NOT NULL,
  `chain_status` enum('pending','generating','complete','failed') NOT NULL DEFAULT 'pending',
  `total_duration_sec` int unsigned NOT NULL,
  `frame_rate` int unsigned NOT NULL,
  `aspect_ratio` enum('16:9','9:16','1:1') NOT NULL,
  `idempotency_key` varchar(128) NOT NULL,
  `input_hash` varchar(64) NOT NULL,
  `request_hash` varchar(64) NOT NULL,
  `request_payload` json NOT NULL,
  `persona_snapshot` json NOT NULL,
  `authorization` json,
  `authorization_closed_at` timestamp(3) NULL,
  `authorization_history` json NOT NULL,
  `lease_token` varchar(36),
  `lease_expires_at` timestamp(3) NULL,
  `next_process_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `last_error` text,
  `failure_stage` varchar(48),
  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `completed_at` timestamp(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `video_chains_owner_idempotency_unique` (`user_id`,`idempotency_key`),
  KEY `video_chains_queue_idx` (`chain_status`,`next_process_at`),
  CONSTRAINT `video_chains_persona_owner_fk` FOREIGN KEY (`persona_id`,`user_id`) REFERENCES `persona_vaults` (`id`,`user_id`) ON DELETE RESTRICT,
  CONSTRAINT `video_chain_duration_positive` CHECK (`total_duration_sec` BETWEEN 3 AND 360),
  CONSTRAINT `video_chain_frame_rate_valid` CHECK (`frame_rate` IN (24,25,30,60))
) ENGINE=InnoDB;
--> statement-breakpoint
CREATE TABLE `video_chain_segments` (
  `id` varchar(36) NOT NULL,
  `chain_id` varchar(36) NOT NULL,
  `segment_order` int unsigned NOT NULL,
  `duration_sec` int unsigned NOT NULL,
  `prompt_text` text NOT NULL,
  `camera_motion_type` varchar(32) NOT NULL,
  `camera_metadata` json NOT NULL,
  `inherited_camera_metadata` json,
  `start_frame_url` text,
  `start_frame_sha256` varchar(64),
  `end_frame_url` text,
  `end_frame_sha256` varchar(64),
  `terminal_frame_extracted_url` text,
  `terminal_frame_sha256` varchar(64),
  `render_job_id` varchar(64),
  `segment_status` enum('pending','generating','extracting','complete','failed','submission_unknown') NOT NULL DEFAULT 'pending',
  `attempt` int unsigned NOT NULL DEFAULT 1,
  `processing_failures` int unsigned NOT NULL DEFAULT 0,
  `stream_url` text,
  `frame_count` int unsigned,
  `actual_duration_sec` double,
  `actual_frame_rate` double,
  `last_error` text,
  `failure_stage` varchar(48),
  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `completed_at` timestamp(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `video_chain_segment_order_unique` (`chain_id`,`segment_order`),
  UNIQUE KEY `video_chain_segments_render_job_id_unique` (`render_job_id`),
  KEY `video_chain_segments_status_idx` (`chain_id`,`segment_status`),
  CONSTRAINT `video_chain_segments_chain_fk` FOREIGN KEY (`chain_id`) REFERENCES `video_generation_chains` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `video_chain_segment_duration_valid` CHECK (`duration_sec` BETWEEN 3 AND 15),
  CONSTRAINT `video_chain_segment_order_positive` CHECK (`segment_order` > 0),
  CONSTRAINT `video_chain_segment_attempt_positive` CHECK (`attempt` > 0)
) ENGINE=InnoDB;
