CREATE TABLE IF NOT EXISTS vaultx_acquisition_config (
  id INT AUTO_INCREMENT PRIMARY KEY,
  config_key VARCHAR(120) NOT NULL UNIQUE,
  config_json JSON NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS vaultx_creator_leads (
  id INT AUTO_INCREMENT PRIMARY KEY,
  uuid VARCHAR(64) NOT NULL UNIQUE,
  platform VARCHAR(64) NOT NULL,
  handle VARCHAR(180) NOT NULL,
  display_name VARCHAR(255),
  profile_url TEXT,
  source VARCHAR(120) NOT NULL DEFAULT 'operator',
  niche VARCHAR(180),
  vertical VARCHAR(100),
  bio TEXT,
  audience_fit_signals JSON,
  recent_activity TEXT,
  followers INT NOT NULL DEFAULT 0,
  engagement_rate DECIMAL(7,2) NOT NULL DEFAULT 0.00,
  monetization_signals JSON,
  platforms JSON,
  telegram_username VARCHAR(180),
  telegram_chat_id VARCHAR(180),
  webhook_url TEXT,
  email VARCHAR(320),
  phone VARCHAR(80),
  score INT NOT NULL DEFAULT 0,
  score_breakdown JSON,
  priority_band VARCHAR(20) NOT NULL DEFAULT 'cold',
  status VARCHAR(40) NOT NULL DEFAULT 'new',
  reply_status VARCHAR(40) NOT NULL DEFAULT 'none',
  follow_up_count INT NOT NULL DEFAULT 0,
  last_outreach_at TIMESTAMP NULL,
  next_follow_up_at TIMESTAMP NULL,
  cta_url TEXT,
  cta_tracking_code VARCHAR(80),
  onboarding_url TEXT,
  handoff_required BOOLEAN NOT NULL DEFAULT FALSE,
  handoff_reason TEXT,
  metadata JSON,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_vaultx_creator_leads_platform_handle (platform, handle),
  KEY idx_vaultx_creator_leads_score (score),
  KEY idx_vaultx_creator_leads_band (priority_band),
  KEY idx_vaultx_creator_leads_status (status),
  KEY idx_vaultx_creator_leads_next_follow (next_follow_up_at)
);

CREATE TABLE IF NOT EXISTS vaultx_outreach_actions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  uuid VARCHAR(64) NOT NULL UNIQUE,
  lead_id INT NOT NULL,
  run_id VARCHAR(64),
  stage VARCHAR(40) NOT NULL,
  channel VARCHAR(40) NOT NULL,
  message TEXT NOT NULL,
  cta_url TEXT,
  status VARCHAR(40) NOT NULL DEFAULT 'queued',
  attempt_count INT NOT NULL DEFAULT 0,
  max_attempts INT NOT NULL DEFAULT 3,
  due_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  sent_at TIMESTAMP NULL,
  external_message_id VARCHAR(255),
  error_message TEXT,
  proof JSON,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_vaultx_actions_due (status, due_at),
  KEY idx_vaultx_actions_lead (lead_id),
  KEY idx_vaultx_actions_run (run_id)
);

CREATE TABLE IF NOT EXISTS vaultx_operator_runs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  run_id VARCHAR(64) NOT NULL UNIQUE,
  mode VARCHAR(40) NOT NULL,
  started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  finished_at TIMESTAMP NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'running',
  sourced_count INT NOT NULL DEFAULT 0,
  scored_count INT NOT NULL DEFAULT 0,
  queued_count INT NOT NULL DEFAULT 0,
  sent_count INT NOT NULL DEFAULT 0,
  failed_count INT NOT NULL DEFAULT 0,
  escalated_count INT NOT NULL DEFAULT 0,
  handoff_count INT NOT NULL DEFAULT 0,
  proof JSON,
  error_message TEXT
);

CREATE TABLE IF NOT EXISTS vaultx_handoff_cases (
  id INT AUTO_INCREMENT PRIMARY KEY,
  uuid VARCHAR(64) NOT NULL UNIQUE,
  lead_id INT NOT NULL,
  run_id VARCHAR(64),
  reason VARCHAR(255) NOT NULL,
  severity VARCHAR(40) NOT NULL DEFAULT 'medium',
  status VARCHAR(40) NOT NULL DEFAULT 'open',
  context JSON,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resolved_at TIMESTAMP NULL,
  KEY idx_vaultx_handoff_status (status),
  KEY idx_vaultx_handoff_lead (lead_id)
);

CREATE TABLE IF NOT EXISTS vaultx_acquisition_telemetry (
  id INT AUTO_INCREMENT PRIMARY KEY,
  event_id VARCHAR(64) NOT NULL UNIQUE,
  run_id VARCHAR(64),
  lead_id INT,
  event_type VARCHAR(80) NOT NULL,
  status VARCHAR(40) NOT NULL,
  source VARCHAR(120),
  score INT,
  priority_band VARCHAR(20),
  channel VARCHAR(40),
  outcome TEXT,
  metadata JSON,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_vaultx_telemetry_event_type (event_type),
  KEY idx_vaultx_telemetry_run (run_id),
  KEY idx_vaultx_telemetry_lead (lead_id),
  KEY idx_vaultx_telemetry_created (created_at)
);
