import { ArrowDown, ArrowLeft, ArrowUpRight, Dumbbell, LockKeyhole, Play, Sparkles } from "lucide-react";
import { Link } from "wouter";

const motion = {
  mirror: "/videos/creator-pages/biggest-b-abs-mirror-source.mp4",
  core: "/videos/creator-pages/biggest-b-dumbbell-core-source.mp4",
};

function Motion({ src, start = 0, className = "" }: { src: string; start?: number; className?: string }) {
  return <video autoPlay muted loop playsInline preload="metadata" onLoadedMetadata={(event) => { event.currentTarget.currentTime = start; }} className={`h-full w-full object-cover ${className}`}><source src={src} type="video/mp4" /></video>;
}

export default function BiggestBWorld() {
  return (
    <main className="min-h-screen overflow-hidden bg-[#f2eee6] text-[#101010]">
      <style>{`
        @keyframes bRise { from { opacity: 0; transform: translateY(35px); } to { opacity: 1; transform: translateY(0); } }
        @keyframes bSpin { to { transform: rotate(360deg); } }
        @keyframes bTicker { from { transform: translateX(0); } to { transform: translateX(-52%); } }
        .b-rise { animation: bRise .82s cubic-bezier(.2,.75,.18,1) both; }
        .b-rise-2 { animation: bRise .82s .14s cubic-bezier(.2,.75,.18,1) both; }
        .b-spin { animation: bSpin 16s linear infinite; }
        .b-ticker { animation: bTicker 18s linear infinite; }
      `}</style>

      <section className="relative isolate min-h-[100svh] overflow-hidden bg-[#090909] text-[#f2eee6]">
        <Motion src={motion.mirror} start={20} />
        <div className="absolute inset-0 bg-[linear-gradient(180deg,rgba(0,0,0,.53),transparent_34%,rgba(0,0,0,.94))]" />
        <div className="absolute -right-24 top-[18%] h-[25rem] w-[25rem] rounded-full border border-[#daff42]/40" />
        <div className="b-spin absolute -right-24 top-[18%] flex h-[25rem] w-[25rem] items-center justify-center text-[9px] font-black uppercase tracking-[.32em] text-[#daff42]/80">CORE · CONSISTENCY · CONDITIONING · CORE · CONSISTENCY · CONDITIONING ·</div>
        <nav className="absolute inset-x-0 top-0 z-10 flex items-center justify-between p-5 sm:p-8"><Link href="/creators"><a className="inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-[.2em] text-white/80"><ArrowLeft className="h-4 w-4" /> The circle</a></Link><p className="text-sm font-black tracking-[-.06em]">CREATOR<span className="text-[#daff42]">VAULT</span></p></nav>
        <div className="absolute inset-x-0 bottom-0 z-10 px-5 pb-10 sm:px-8 lg:px-12 lg:pb-14"><div className="mx-auto max-w-7xl"><p className="b-rise mb-4 flex items-center gap-2 text-[10px] font-black uppercase tracking-[.24em] text-[#daff42]"><span className="h-2 w-2 rounded-full bg-[#daff42]" /> @IAMTHE_BCB / REAL PUBLIC SOURCE</p><h1 className="b-rise-2 max-w-5xl text-[21vw] font-black leading-[.7] tracking-[-.13em] sm:text-[10rem] lg:text-[14rem]">THE<br /><span className="text-[#daff42]">BIGGEST</span><br />B.</h1><p className="b-rise-2 mt-7 max-w-xl text-lg font-semibold leading-7 text-white/75">Her abs are not a prop. They are the signature. The source is real. The work is real. The fan pull is already moving.</p><div className="b-rise-2 mt-8 flex flex-wrap gap-3"><a href="https://www.snapchat.com/@iamthe_bcb" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full bg-[#daff42] px-6 py-3 text-sm font-black text-black">Follow the source <ArrowUpRight className="h-4 w-4" /></a><a href="#study" className="inline-flex items-center gap-2 rounded-full border border-white/30 bg-black/20 px-6 py-3 text-sm font-black backdrop-blur"><ArrowDown className="h-4 w-4" /> See the study</a></div></div></div>
      </section>

      <section className="overflow-hidden bg-[#daff42] py-4 text-black"><div className="b-ticker flex w-max gap-8 whitespace-nowrap text-xs font-black uppercase tracking-[.25em]"><span>ABS ARE THE STORY</span><span>✦</span><span>NOT A FITNESS TEMPLATE</span><span>✦</span><span>BODY CINEMA FIELD STUDY 01</span><span>✦</span><span>THE SOURCE STAYS HERS</span><span>✦</span><span>ABS ARE THE STORY</span><span>✦</span><span>NOT A FITNESS TEMPLATE</span><span>✦</span><span>BODY CINEMA FIELD STUDY 01</span><span>✦</span><span>THE SOURCE STAYS HERS</span></div></section>

      <section className="relative min-h-[105svh] bg-[#f2eee6] px-5 py-16 sm:px-8 lg:px-12 lg:py-24"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.78fr_1.22fr] lg:items-end"><div className="lg:pb-10"><p className="text-xs font-black uppercase tracking-[.24em] text-[#546716]">01 / The core is the camera language</p><h2 className="mt-5 text-[17vw] font-black leading-[.72] tracking-[-.11em] sm:text-[8rem]">BUILT.<br />NOT<br /><span className="text-[#7a1e39]">BORROWED.</span></h2><p className="mt-8 max-w-sm text-lg leading-8 text-black/70">This world starts where hers starts: with real training, visible discipline, and a body she already knows how to turn into attention.</p></div><div className="relative aspect-[4/5] overflow-hidden rounded-[3.2rem] bg-black shadow-[18px_20px_0_#101010]"><Motion src={motion.core} /><div className="absolute inset-0 bg-gradient-to-t from-black/70 via-transparent to-transparent" /><div className="absolute bottom-6 left-6 right-6 flex items-end justify-between"><p className="max-w-[14rem] text-3xl font-black leading-[.83] tracking-[-.07em] text-white">THE CAMERA STAYS ON THE WORK.</p><Dumbbell className="h-8 w-8 text-[#daff42]" /></div></div></div></section>

      <section id="study" className="relative overflow-hidden bg-[#151515] px-5 py-20 text-[#f2eee6] sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto max-w-7xl"><div className="grid gap-10 lg:grid-cols-[1.1fr_.9fr] lg:items-start"><div><p className="text-xs font-black uppercase tracking-[.24em] text-[#daff42]">Body Cinema / field study 01</p><h2 className="mt-5 max-w-4xl text-[15vw] font-black leading-[.74] tracking-[-.11em] sm:text-8xl">A BODY<br />WITH A<br /><span className="text-[#daff42]">LIBRARY.</span></h2></div><div className="border-l border-white/20 pl-6 lg:mt-16"><p className="text-2xl font-black leading-[.9] tracking-[-.06em]">B has enough real material to make the fitness/adult lane mean something.</p><p className="mt-6 text-base leading-7 text-white/65">The first source study is locked to her verified public gym footage. Her face, body, clothing, movement, camera angle, and gym space stay protected. No finished Body Cinema transformation is being claimed here until one passes the real review.</p></div></div><div className="mt-14 grid gap-5 lg:grid-cols-[1.55fr_.45fr]"><div className="relative aspect-[16/10] overflow-hidden rounded-[2.4rem] border border-white/15 bg-black"><Motion src={motion.mirror} /><div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent" /><div className="absolute bottom-6 left-6 right-6 flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-[.22em] text-[#daff42]">Source locked</p><p className="mt-2 text-3xl font-black leading-[.85] tracking-[-.06em]">ABS / MIRROR / GYM</p></div><LockKeyhole className="h-7 w-7 text-[#daff42]" /></div></div><div className="flex min-h-[16rem] flex-col justify-between rounded-[2.4rem] bg-[#daff42] p-7 text-black"><Sparkles className="h-8 w-8" /><div><p className="text-5xl font-black leading-[.75] tracking-[-.1em]">01</p><p className="mt-4 text-xs font-black uppercase tracking-[.2em]">Study source / verified public clip</p></div></div></div></div></section>

      <section className="relative bg-[#7a1e39] px-5 py-20 text-[#f7e9df] sm:px-8 lg:px-12"><div className="mx-auto max-w-7xl"><p className="text-xs font-black uppercase tracking-[.24em] text-[#daff42]">Every channel is part of the machine</p><div className="mt-7 flex flex-col gap-0 border-y border-[#f7e9df]/25"><a className="group flex items-center justify-between py-6 text-3xl font-black tracking-[-.07em] sm:text-5xl" href="https://www.snapchat.com/@iamthe_bcb" target="_blank" rel="noreferrer"><span>SNAP / @IAMTHE_BCB</span><ArrowUpRight className="h-7 w-7 transition-transform group-hover:-translate-y-1 group-hover:translate-x-1" /></a><a className="group flex items-center justify-between border-t border-[#f7e9df]/25 py-6 text-3xl font-black tracking-[-.07em] sm:text-5xl" href="https://x.com/Roxiee102" target="_blank" rel="noreferrer"><span>X / @ROXIEE102</span><ArrowUpRight className="h-7 w-7 transition-transform group-hover:-translate-y-1 group-hover:translate-x-1" /></a><a className="group flex items-center justify-between border-t border-[#f7e9df]/25 py-6 text-3xl font-black tracking-[-.07em] sm:text-5xl" href="https://onlyfans.com/luvroxie" target="_blank" rel="noreferrer"><span>MEMBERSHIP / LUVROXIE</span><ArrowUpRight className="h-7 w-7 transition-transform group-hover:-translate-y-1 group-hover:translate-x-1" /></a></div><p className="mt-9 max-w-2xl text-lg leading-8 text-[#f7e9df]/75">The point is not to make her look like a new fitness creator. She already has a world. CreatorVault is where it becomes a protected, premium creation library.</p></div></section>
    </main>
  );
}
