import { useMemo, useState } from "react";
import { Link, useLocation } from "wouter";
import { Activity, ArrowLeft, ArrowRight, Brain, CheckCircle2, Clapperboard, Crown, Film, LockKeyhole, Mic2, Play, ShieldCheck, Sparkles, Vault, Wand2 } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/contexts/AuthContext";
import { KingCamPerformanceCapture } from "@/components/KingCamPerformanceCapture";

const roomIcons = {
  "creator-ownership": Crown,
  "body-cinema": Film,
  "caption-stage": Mic2,
  "trailer-maker": Clapperboard,
  "clone-command": Wand2,
} as const;

function StatusPill({ value }: { value: string }) {
  const state = value.toLowerCase();
  const tone = state.includes("live") || state.includes("ready") || state.includes("accepted") ? "border-emerald-300/35 bg-emerald-300/10 text-emerald-200" : state.includes("progress") || state.includes("planned") ? "border-amber-200/30 bg-amber-200/10 text-amber-100" : "border-white/20 bg-white/5 text-white/65";
  return <span className={`inline-flex rounded-full border px-2.5 py-1 text-[9px] font-black uppercase tracking-[.15em] ${tone}`}>{value.replace(/_/g, " ")}</span>;
}

export default function KingCamClone() {
  const [, setLocation] = useLocation();
  const { user } = useAuth();
  const isOwner = user?.id === 6 || user?.id === 33 || user?.role === "king" || user?.role === "admin";
  const [notice, setNotice] = useState<string | null>(null);
  const command = trpc.kingcamCloneOperatingSystem.getCommandCenter.useQuery(undefined, { enabled: isOwner, retry: false });
  const training = trpc.kingcamCloneOperatingSystem.getTrainingLibrary.useQuery(undefined, { enabled: isOwner, retry: false });
  const beginTour = trpc.kingcamCloneOperatingSystem.beginTour.useMutation({
    onSuccess: (result) => { setNotice(`KingCam has entered ${result.room.room}.`); command.refetch(); setLocation(result.nextAction); },
    onError: (error) => setNotice(error.message),
  });
  const system = command.data;
  const sourceCount = useMemo(() => system?.identityVault?.approvedIdentityAssets?.length || 0, [system]);
  const bodyLibrary = training.data;

  if (!isOwner) {
    return <main className="min-h-screen bg-[#080506] px-6 py-12 text-[#fff8eb]"><div className="mx-auto max-w-xl rounded-[2rem] border border-[#d9a44e]/25 bg-[#160b0b] p-8 text-center"><Crown className="mx-auto h-9 w-9 text-[#e7bc70]" /><h1 className="mt-5 text-4xl font-black tracking-[-.07em]">KINGCAM CLONE</h1><p className="mt-4 leading-7 text-white/65">KingCam Clone Command is his protected CreatorVault control room. The public KingCam guide is open for the platform tour.</p><Link href="/kingcam/guide"><a className="mt-7 inline-flex min-h-12 items-center gap-2 rounded-full bg-[#d9a44e] px-6 text-sm font-black text-black"><Play className="h-4 w-4 fill-current" /> Enter the guide</a></Link></div></main>;
  }

  return (
    <main className="min-h-screen overflow-hidden bg-[#080506] text-[#fff8eb]">
      <style>{`
        @keyframes kc-rise { from { opacity: 0; transform: translateY(20px); } to { opacity: 1; transform: translateY(0); } }
        @keyframes kc-orbit { 0%,100% { transform: rotate(0deg) scale(1); opacity:.32; } 50% { transform: rotate(10deg) scale(1.08); opacity:.56; } }
        .kc-rise { animation: kc-rise .7s cubic-bezier(.16,.82,.2,1) both; }
        .kc-orbit { animation: kc-orbit 9s ease-in-out infinite; }
        @media (prefers-reduced-motion: reduce) { .kc-rise,.kc-orbit { animation:none; } }
      `}</style>
      <section className="relative isolate overflow-hidden border-b border-[#d9a44e]/20 bg-[radial-gradient(circle_at_76%_18%,rgba(150,25,38,.42),transparent_29%),linear-gradient(135deg,#120606,#080506_58%,#16100b)] px-5 pb-14 pt-6 sm:px-8 sm:pb-20 lg:px-12">
        <div className="kc-orbit pointer-events-none absolute -right-32 top-[-10rem] h-[34rem] w-[34rem] rounded-full border border-[#e8bd74]/25 bg-[#a20e23]/20 blur-3xl" />
        <div className="relative mx-auto max-w-7xl">
          <header className="flex items-center justify-between gap-4"><Link href="/kingcam"><a className="inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-[.2em] text-white/75"><ArrowLeft className="h-4 w-4" /> KingCam</a></Link><StatusPill value={system?.status || "loading"} /></header>
          <div className="mt-16 grid gap-10 lg:grid-cols-[1.15fr_.85fr] lg:items-end">
            <div className="kc-rise"><p className="text-[10px] font-black uppercase tracking-[.3em] text-[#e8bd74]">CreatorVault / KingCam Clone Operating System</p><h1 className="mt-6 text-[16vw] font-black leading-[.66] tracking-[-.12em] sm:text-8xl lg:text-[7.8rem]">NOT A<br /><span className="text-[#e1ac58]">TOY.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-white/70">This is the command center for the full KingCam system: your identity, body, real voice, cinematic motion, platform knowledge, memory, truth rules, and quality decisions—all owned by CreatorVault.</p><div className="mt-8"><KingCamPerformanceCapture /></div>{notice && <p className="mt-5 max-w-xl rounded-2xl border border-[#e8bd74]/25 bg-black/35 px-4 py-3 text-sm leading-6 text-[#f6dfaf]">{notice}</p>}</div>
            <aside className="kc-rise rounded-[2rem] border border-[#e8bd74]/25 bg-black/35 p-6 backdrop-blur-xl"><p className="text-[9px] font-black uppercase tracking-[.23em] text-[#e8bd74]">The real KingCam spine</p><div className="mt-6 space-y-4"><div className="flex items-start gap-3"><Crown className="mt-0.5 h-5 w-5 text-[#e8bd74]" /><div><p className="font-black">Identity Vault</p><p className="mt-1 text-sm leading-5 text-white/55">{sourceCount} approved KingCam identity sources. None is counted as a body driver unless it passes the real-performance gate.</p></div></div><div className="flex items-start gap-3"><Mic2 className="mt-0.5 h-5 w-5 text-[#e8bd74]" /><div><p className="font-black">Real voice only</p><p className="mt-1 text-sm leading-5 text-white/55">Your ElevenLabs clone is the voice lane. A generic fallback is not allowed for public KingCam.</p></div></div><div className="flex items-start gap-3"><Film className="mt-0.5 h-5 w-5 text-[#e8bd74]" /><div><p className="font-black">Full-body motion</p><p className="mt-1 text-sm leading-5 text-white/55">The next full-body clone proof starts from your real recorded performance—crown to shoes, real voice, real gait, real hands—not a model guessing your body.</p></div></div><div className="flex items-start gap-3"><Brain className="mt-0.5 h-5 w-5 text-[#e8bd74]" /><div><p className="font-black">Truth and memory</p><p className="mt-1 text-sm leading-5 text-white/55">KingCam leads people only through real CreatorVault rooms and stores owner-directed launch decisions inside his own command history.</p></div></div></div></aside>
          </div>
        </div>
      </section>

      <section className="bg-[#110908] px-5 py-14 sm:px-8 lg:px-12"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-6"><div><p className="text-[10px] font-black uppercase tracking-[.25em] text-[#e8bd74]">The truth library</p><h2 className="mt-4 text-5xl font-black tracking-[-.09em] sm:text-7xl">KINGCAM KNOWS<br />WHAT IS <span className="text-[#e1ac58]">REAL.</span></h2></div><p className="max-w-md text-base leading-7 text-white/60">The clone does not make up a feature, a buyer, a subscriber count, a provider result, or a creator outcome. Every room below carries its real condition with it.</p></div><div className="mt-10 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{(system?.truthLibrary || []).map((room) => { const Icon = roomIcons[room.id as keyof typeof roomIcons] || Sparkles; return <article key={room.id} className="group flex min-h-[17rem] flex-col rounded-[2rem] border border-white/10 bg-white/[.035] p-6 transition hover:-translate-y-1 hover:border-[#e8bd74]/45"><div className="flex items-start justify-between gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-[#d9a44e]/12 text-[#e8bd74]"><Icon className="h-5 w-5" /></span><StatusPill value={room.proofState} /></div><h3 className="mt-8 text-2xl font-black tracking-[-.06em]">{room.room}</h3><p className="mt-3 flex-1 text-sm leading-6 text-white/60">{room.fact}</p><button type="button" disabled={beginTour.isPending} onClick={() => beginTour.mutate({ roomId: room.id as "creator-ownership" | "body-cinema" | "caption-stage" | "trailer-maker" | "clone-command" })} className="mt-5 inline-flex items-center gap-2 text-left text-[10px] font-black uppercase tracking-[.16em] text-[#f0cc87]"><ArrowRight className="h-4 w-4" /> Let KingCam enter this room</button></article>; })}</div></div></section>

      <section className="border-y border-[#e8bd74]/20 bg-[#0d0808] px-5 py-14 sm:px-8 lg:px-12"><div className="mx-auto max-w-7xl"><div className="grid gap-10 lg:grid-cols-[.75fr_1.25fr] lg:items-end"><div><p className="text-[10px] font-black uppercase tracking-[.25em] text-[#e8bd74]">KingCam body library</p><h2 className="mt-4 text-5xl font-black leading-[.76] tracking-[-.1em] sm:text-7xl">ONLY REAL<br /><span className="text-[#e1ac58]">MOTION</span><br />TEACHES HIM.</h2></div><p className="max-w-xl text-base leading-7 text-white/60">Your clone keeps the right materials and locks weak material out. A clean identity look can teach the look. Only a real full-body KingCam performance can teach the body, hands, gait, and presence.</p></div><div className="mt-10 grid gap-4 md:grid-cols-3"><article className="rounded-[2rem] border border-[#e8bd74]/25 bg-[#e8bd74]/[.07] p-6"><Crown className="h-6 w-6 text-[#e8bd74]" /><p className="mt-7 text-[10px] font-black uppercase tracking-[.18em] text-[#e8bd74]">Look held</p><p className="mt-3 text-4xl font-black tracking-[-.08em]">{bodyLibrary?.summary.identityReferences ?? 0}</p><p className="mt-3 text-sm leading-6 text-white/55">Approved identity material stays in the vault to hold your face, crown, fit, and presence steady.</p></article><article className="rounded-[2rem] border border-white/10 bg-white/[.035] p-6"><ShieldCheck className="h-6 w-6 text-[#e8bd74]" /><p className="mt-7 text-[10px] font-black uppercase tracking-[.18em] text-[#e8bd74]">Locked out</p><p className="mt-3 text-4xl font-black tracking-[-.08em]">{bodyLibrary?.summary.rejectedSynthetic ?? 0}</p><p className="mt-3 text-sm leading-6 text-white/55">Old artificial clips stay out of the body lane. They cannot teach KingCam to move.</p></article><article className="rounded-[2rem] border border-[#a70f2a]/40 bg-[#a70f2a]/10 p-6"><Activity className="h-6 w-6 text-[#f2b9c3]" /><p className="mt-7 text-[10px] font-black uppercase tracking-[.18em] text-[#f2b9c3]">Body driver</p><p className="mt-3 text-2xl font-black tracking-[-.06em]">{bodyLibrary?.summary.motionDriverReady ? "READY" : "REAL TAKE NEXT"}</p><p className="mt-3 text-sm leading-6 text-white/60">Your direct Performance Capture is the only path that can become the real full-body KingCam movement source.</p></article></div></div></section>

      <section className="relative overflow-hidden bg-[#e8c37f] px-5 py-14 text-[#180b08] sm:px-8 lg:px-12"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-start"><div><p className="text-[10px] font-black uppercase tracking-[.25em] text-[#8a271c]">The quality oath</p><h2 className="mt-4 text-5xl font-black leading-[.75] tracking-[-.1em] sm:text-7xl">IF IT DOESN'T<br />LOOK LIKE<br /><span className="text-[#8a271c]">KINGCAM,</span><br />IT'S OUT.</h2></div><div className="grid gap-3">{(system?.qualityPolicy?.gates || []).map((gate: string, index: number) => <div key={gate} className="flex gap-4 rounded-2xl border border-[#4b170f]/15 bg-white/35 p-5"><span className="font-black text-[#8a271c]">0{index + 1}</span><p className="text-sm font-semibold leading-6 text-[#31130d]/80">{gate}</p></div>)}</div></div></section>

      <section className="bg-[#090506] px-5 py-14 sm:px-8 lg:px-12"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-6"><div><p className="text-[10px] font-black uppercase tracking-[.25em] text-[#e8bd74]">Motion proof ledger</p><h2 className="mt-4 text-5xl font-black tracking-[-.09em] sm:text-7xl">NO HIDDEN<br /><span className="text-[#e1ac58]">GENERATION.</span></h2></div><div className="max-w-md rounded-2xl border border-white/10 bg-white/[.035] p-5 text-sm leading-6 text-white/60"><ShieldCheck className="mb-3 h-5 w-5 text-[#e8bd74]" />Every full-body request records source, model lane, one-output cap, credit ceiling, consent, ownership, and final accept-or-reject decision before it ever becomes public KingCam media.</div></div><div className="mt-8 grid gap-4 lg:grid-cols-2">{(system?.motionRequests || []).length ? (system?.motionRequests || []).map((request) => <article key={request.id} className="rounded-[2rem] border border-white/10 bg-white/[.035] p-6"><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-xs font-black uppercase tracking-[.18em] text-[#e8bd74]">{request.intendedLane.replace(/_/g, " ")}</p><StatusPill value={request.state} /></div><p className="mt-4 text-lg font-black">Full-body KingCam proof</p><p className="mt-3 text-sm leading-6 text-white/60">{request.sceneBrief}</p><div className="mt-5 flex flex-wrap gap-2">{request.candidateModels.map((model: string) => <span key={model} className="rounded-full border border-white/15 px-3 py-1 text-[9px] font-black uppercase tracking-[.12em] text-white/60">{model.replace("pollo/", "")}</span>)}<span className="rounded-full border border-[#e8bd74]/35 bg-[#e8bd74]/10 px-3 py-1 text-[9px] font-black uppercase tracking-[.12em] text-[#f0cf91]">{request.hardCreditCap} credit ceiling</span></div></article>) : <div className="rounded-[2rem] border border-dashed border-white/20 bg-white/[.025] p-8 text-center"><Vault className="mx-auto h-7 w-7 text-[#e8bd74]" /><p className="mt-4 text-xl font-black">THE FIRST FULL-BODY PROOF IS NOT FAKE.</p><p className="mx-auto mt-3 max-w-lg text-sm leading-6 text-white/55">Lock it here first. The governed motion lane will refuse to create until source, consent, spend ceiling, model, and quality law are all recorded.</p></div>}</div></div></section>
    </main>
  );
}
