CREATE TABLE IF NOT EXISTS `creator_conversion_intelligence` (
  `id` int AUTO_INCREMENT NOT NULL,
  `profile_id` int NOT NULL,
  `niche_classification` varchar(180) NOT NULL,
  `monetization_gaps` json NOT NULL,
  `estimated_lost_revenue_cents` int NOT NULL DEFAULT 0,
  `audience_quality_score` int NOT NULL DEFAULT 0,
  `subscription_opportunity_score` int NOT NULL DEFAULT 0,
  `vip_opportunity_score` int NOT NULL DEFAULT 0,
  `telegram_opportunity_score` int NOT NULL DEFAULT 0,
  `clone_opportunity_score` int NOT NULL DEFAULT 0,
  `recurring_revenue_potential_cents` int NOT NULL DEFAULT 0,
  `creator_maturity_level` varchar(80) NOT NULL,
  `onboarding_difficulty_score` int NOT NULL DEFAULT 0,
  `conversion_probability_score` int NOT NULL DEFAULT 0,
  `signal_snapshot` json NOT NULL,
  `generated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `creator_conversion_intelligence_id` PRIMARY KEY(`id`),
  CONSTRAINT `uniq_conversion_intelligence_profile` UNIQUE(`profile_id`),
  CONSTRAINT `fk_conversion_intelligence_profile` FOREIGN KEY (`profile_id`) REFERENCES `recruiter_creator_profiles`(`id`) ON DELETE CASCADE,
  KEY `idx_conversion_intelligence_probability` (`conversion_probability_score`),
  KEY `idx_conversion_intelligence_revenue` (`recurring_revenue_potential_cents`)
);

CREATE TABLE IF NOT EXISTS `creator_conversion_packets` (
  `id` int AUTO_INCREMENT NOT NULL,
  `profile_id` int NOT NULL,
  `intelligence_id` int,
  `packet_status` varchar(40) NOT NULL DEFAULT 'generated',
  `personalized_social_audit` text NOT NULL,
  `monetization_leak_analysis` text NOT NULL,
  `recurring_revenue_opportunity` text NOT NULL,
  `telegram_opportunity` text NOT NULL,
  `ai_clone_opportunity` text NOT NULL,
  `vip_funnel_opportunity` text NOT NULL,
  `platform_growth_opportunity` text NOT NULL,
  `creatorvault_leverage_explanation` text NOT NULL,
  `personalized_trailer_brief` text NOT NULL,
  `cinematic_onboarding_preview` text NOT NULL,
  `monetization_visuals` json NOT NULL,
  `connected_systems` json NOT NULL,
  `generated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `creator_conversion_packets_id` PRIMARY KEY(`id`),
  CONSTRAINT `uniq_conversion_packets_profile` UNIQUE(`profile_id`),
  CONSTRAINT `fk_conversion_packets_profile` FOREIGN KEY (`profile_id`) REFERENCES `recruiter_creator_profiles`(`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_conversion_packets_intelligence` FOREIGN KEY (`intelligence_id`) REFERENCES `creator_conversion_intelligence`(`id`) ON DELETE SET NULL,
  KEY `idx_conversion_packets_status` (`packet_status`)
);

CREATE TABLE IF NOT EXISTS `creator_conversion_automation` (
  `id` int AUTO_INCREMENT NOT NULL,
  `profile_id` int NOT NULL,
  `packet_id` int,
  `assigned_recruiter` varchar(160),
  `follow_up_cadence` json NOT NULL,
  `next_follow_up_at` timestamp NULL,
  `last_response_signal` varchar(120),
  `interest_score` int NOT NULL DEFAULT 0,
  `onboarding_stage` varchar(80) NOT NULL DEFAULT 'packet_generated',
  `onboarding_stage_history` json NOT NULL,
  `telegram_transition_status` varchar(80) NOT NULL DEFAULT 'not_started',
  `telegram_transition_target` varchar(255),
  `conversion_stage` varchar(80) NOT NULL DEFAULT 'queued',
  `stripe_activation_status` varchar(80) NOT NULL DEFAULT 'not_started',
  `stripe_activation_reference` varchar(255),
  `money_next_action` varchar(255) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `creator_conversion_automation_id` PRIMARY KEY(`id`),
  CONSTRAINT `uniq_conversion_automation_profile` UNIQUE(`profile_id`),
  CONSTRAINT `fk_conversion_automation_profile` FOREIGN KEY (`profile_id`) REFERENCES `recruiter_creator_profiles`(`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_conversion_automation_packet` FOREIGN KEY (`packet_id`) REFERENCES `creator_conversion_packets`(`id`) ON DELETE SET NULL,
  KEY `idx_conversion_automation_stage` (`onboarding_stage`),
  KEY `idx_conversion_automation_conversion` (`conversion_stage`),
  KEY `idx_conversion_automation_next_follow` (`next_follow_up_at`)
);

CREATE TABLE IF NOT EXISTS `creator_high_ticket_packages` (
  `id` int AUTO_INCREMENT NOT NULL,
  `package_key` varchar(80) NOT NULL,
  `package_name` varchar(180) NOT NULL,
  `description` text NOT NULL,
  `existing_systems` json NOT NULL,
  `price_floor_cents` int NOT NULL DEFAULT 0,
  `recurring_potential_cents` int NOT NULL DEFAULT 0,
  `money_trigger` varchar(255) NOT NULL,
  `activation_route` varchar(255) NOT NULL,
  `is_active` boolean NOT NULL DEFAULT true,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `creator_high_ticket_packages_id` PRIMARY KEY(`id`),
  CONSTRAINT `uniq_high_ticket_package_key` UNIQUE(`package_key`),
  KEY `idx_high_ticket_packages_active` (`is_active`)
);

CREATE TABLE IF NOT EXISTS `creator_acquisition_priorities` (
  `id` int AUTO_INCREMENT NOT NULL,
  `profile_id` int NOT NULL,
  `intelligence_id` int,
  `priority_score` int NOT NULL DEFAULT 0,
  `priority_band` varchar(40) NOT NULL DEFAULT 'medium',
  `monetization_potential_score` int NOT NULL DEFAULT 0,
  `likelihood_to_convert_score` int NOT NULL DEFAULT 0,
  `revenue_leakage_score` int NOT NULL DEFAULT 0,
  `operational_maturity_score` int NOT NULL DEFAULT 0,
  `engagement_quality_score` int NOT NULL DEFAULT 0,
  `telegram_readiness_score` int NOT NULL DEFAULT 0,
  `recurring_revenue_score` int NOT NULL DEFAULT 0,
  `paid_audience_behavior_score` int NOT NULL DEFAULT 0,
  `ranking_reason` text NOT NULL,
  `next_money_action` varchar(255) NOT NULL,
  `scored_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `creator_acquisition_priorities_id` PRIMARY KEY(`id`),
  CONSTRAINT `uniq_acquisition_priority_profile` UNIQUE(`profile_id`),
  CONSTRAINT `fk_acquisition_priority_profile` FOREIGN KEY (`profile_id`) REFERENCES `recruiter_creator_profiles`(`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_acquisition_priority_intel` FOREIGN KEY (`intelligence_id`) REFERENCES `creator_conversion_intelligence`(`id`) ON DELETE SET NULL,
  KEY `idx_acquisition_priorities_score` (`priority_score`),
  KEY `idx_acquisition_priorities_band` (`priority_band`)
);
